### ISSUE TITLE
Need code which will apply target selection cuts on grzW1W2 *fluxes*

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#1]
The function cuts.select_target() takes as input grz magnitudes, but we need something which can be applied to the DECaLS catalogs, which report grz fluxes in nanomaggies (which can be negative).  

The flux version of the current set of cuts are here:
  https://desi.lbl.gov/trac/wiki/TargetSelection

**Comment by djschlegel** [comment]
Yu Feng's implementation documented with examples here:
http://desihub.github.io/imaginglss/

**Comment by moustakas** [comment]
That functionality used to be there (in analysis.cuts()) but doesn't seem to be there anymore.  I've posted an issue to imaginglss, but separate from this do we want a dependence in desitarget on imaginglss?  My inclination is that imaginglss could/should depend on desitarget, but not the other way around.

**Comment by djschlegel** [comment]
John,

Re-factoring that way would be good, e.g. moving some of Yu Feng’s functions
into desitarget.

Note Yu Feng has been careful to exclude regions wherever the depth cut isn’t
met in any band.  In practice, I think we include those regions with shallower depth,
and then either mask or otherwise deal with it downstream.  After all, unlike SDSS,
there’s no avoiding patches on the sky by plugging elsewhere.

-David

**Comment by rainwoodman** [comment]
We can probably just pass the depth downstream.

The implementations of the TargetSelection wiki page in imaginglss is there:

https://github.com/desihub/imaginglss/blob/master/imaginglss/analysis/targetselection.py

The main script is 

https://github.com/desihub/imaginglss/blob/master/scripts/select_objs.py

I believe you can ask for any sigma level confidence as a parameter. (-sigma-z, ...)

My version doesn't use the depth information in the catalogue since I expect to read the depth-images for 'randoms' as well. Since you don't deal with randoms, you don't need this complication.

**Comment by rainwoodman** [comment]
But are we surely will define targets in insufficiently deep areas?

**Comment by rainwoodman** [comment]
I looked at this and seems like the easiest solution is to convert the input to a dictionary. 

If not opposed I will file a PR?

**Comment by rainwoodman** [comment]
I attempted but find this won't magically switch to nanomaggies, thus give up.

What if I just port the code in imaginglss here?

**Comment by sbailey** [comment]
Pull request #2 addresses this with example cuts on fluxes.  Closing this ticket.  Please open new tickets for other specific issues.
