### ISSUE TITLE
fix incorrect QSO selection test

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#100]
**Summary**: `desitarget.test.test_cuts` function `test_single_cuts` is incorrectly testing that QSO target selection does not depend upon `deltaChi2` nor `wise_snr`.  Fix that.

**Background**:  originally `cuts.isQSO` allowed `primary` and `objtype` (psftype) to be optional parameters as a minor convenience for template generation so that it could focus on the fluxes and not have to also pass in arrays of primary=True and objtype='PSF'.  A test confirmed that the selection would work with or without them.

**Current problem**: Since then, `cuts.isQSO` gained two more optional parameters `deltaChi2` and `wise_snr`.  The tests were expanded to include those as optional, but incorrectly is testing that they don't make any difference:
```python
        qso1 = cuts.isQSO(gflux=gflux, rflux=rflux, zflux=zflux, w1flux=w1flux, w2flux=w2flux,
                          objtype=psftype, primary=primary, deltaChi2=deltaChi2, wise_snr=wise_snr)
        qso2 = cuts.isQSO(gflux=gflux, rflux=rflux, zflux=zflux, w1flux=w1flux, w2flux=w2flux,
                          objtype=None, primary=None, deltaChi2=None, wise_snr=None)
        self.assertTrue(np.all(qso1==qso2))

```
This accidentally passes for some but not all of the test sweep files in `test/t`.  It turns out that our tests use `os.walk` under the hood to grab the first sweep file it finds, and which file gets selected depends upon where the code is installed.  I accidentally tripped over this yesterday when I found that the identical code installed on edison $SCRATCH failed tests while it worked when installed under $HOME... :(

Also note that `cuts.isQSO` uses `wise_snr` but `cuts.isQSO_randomforest` does not.

To do:
* Decide if these really should be optional parameters, or whether they should be required since they actually are used in the cuts, even if that is a minor inconvenience for template generation.
  * Stephen's opinion: `primary` feels like a deprecated leftover of an earlier imaging data release; I'm ok with that being optional.  The others probably should become genuinely required arguments.
* Fix the tests

**Comment by Cyeche** [comment]
> Summary: desitarget.test.test_cuts function test_single_cuts is incorrectly testing that QSO target selection does not depend upon deltaChi2 nor wise_snr. Fix that.
> 
> Background: originally cuts.isQSO allowed primary and objtype (psftype) to be optional parameters as a minor convenience for template generation so that it could focus on the fluxes and not have to also pass in arrays of primary=True and objtype='PSF'. A test confirmed that the selection would work with or without them.
> 
> Current problem: Since then, cuts.isQSO gained two more optional parameters deltaChi2 and wise_snr. The tests were expanded to include those as optional, but incorrectly is testing that they don't make any difference:
> 
>         qso1 = cuts.isQSO(gflux=gflux, rflux=rflux, zflux=zflux, w1flux=w1flux, w2flux=w2flux,
>                           objtype=psftype, primary=primary, deltaChi2=deltaChi2, wise_snr=wise_snr)
>         qso2 = cuts.isQSO(gflux=gflux, rflux=rflux, zflux=zflux, w1flux=w1flux, w2flux=w2flux,
>                           objtype=None, primary=None, deltaChi2=None, wise_snr=None)
>         self.assertTrue(np.all(qso1==qso2))


As the test the tests on  deltaChi2 and wise_snr are not mandatory and as we just want to see the effect of  requiring   PSF  type object, I would be  in favor  of just testing PSF (we can remove the primary object test because primary seems to be deprecated…) Therefore we just need:

 qso2 = cuts.isQSO(gflux=gflux, rflux=rflux, zflux=zflux, w1flux=w1flux, w2flux=w2flux,
                          objtype=None, primary=primary, deltaChi2=deltaChi2, wise_snr=wise_snr)





> This accidentally passes for some but not all of the test sweep files in test/t. It turns out that our tests use os.walk under the hood to grab the first sweep file it finds, and which file gets selected depends upon where the code is installed. I accidentally tripped over this yesterday when I found that the identical code installed on edison $SCRATCH failed tests while it worked when installed under $HOME... :(
> 
> Also note that cuts.isQSO uses wise_snr but cuts.isQSO_randomforest does not.
> 
> 
> 
wise_snr is not used with random forest algorithm…

Christophe.

**Comment by moustakas** [comment]
The templates aren't properly using these cuts anyway since the QSO templates don't extend into the mid-IR (see https://github.com/desihub/desisim/issues/152), but it seems like this issue could be resolved if we segregated the color-cuts (whether the "pure" color-cuts or those based on the Random Forest) from the other catalog-level cuts on morphology (aka ```deltaChi2```) and ```wise_snr```.  

For example, the templates code could call an ```isQSO_colors()``` function whereas ```isQSO()``` could take the output Boolean array from ```isQSO_colors()``` and apply any additional catalog-level cuts.  Doing this refactor (@Cyeche?) and fixing the tests should then be trivial.  Thoughts?
