### ISSUE TITLE
Generate target density fluctuations

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#101]
Generate brick-by-brick depth fluctuations and density fluctuations that are correlated with those depths and E(B-V).  Define file format for how those are passed off from @geordie666 to `select_mock_targets`.  0th order would be a FITS binary table with columns:
* BRICKNAME
* EBV (median E(B-V) of the brick; or do we want to do it at the per-target level from the start?)
* DEPTH_G, DEPTH_R, DEPTH_Z, GALDEPTH_G, GALDEPTH_R, GALDEPTH_Z (use DR3 definition of point-source and galaxy depth; I don't see WISE depths included in DR3 sweeps...)
* DENSITY_ELG, DENSITY_LRG, DENSITY_QSO, DENSITY_LYA, DENSITY_BGS, DENSITY_MWS
* DENSITY_BAD_ELG, DENSITY_BAD_LRG, DENSITY_BAD_QSO, DENSITY_BAD_LYA, DENSITY_BAD_BGS, DENSITY_BAD_MWS
  * some of these may be all zeros, e.g. DENSITY_BAD_MWS
  * different name than "BAD"?  FAKE?  CONTAMINANT seems too long...

Note: This isn't completely flexible for being able to specify densities for different flavors of bright vs. faint BGS, MWS FSTAR vs. WD, etc. nor what type of contaminants to use, but I think it is a good start for the purposes of the December meeting.

**Comment by forero** [comment]
What will be the units for the depths? magnitudes? fluxes?

**Comment by geordie666** [comment]
5-sigma AB depth in magnitudes.

**Comment by forero** [comment]
Here is a [first try to generate mock density fluctuations](https://github.com/desihub/desitarget/blob/ed9a490f84ad6118225d3a60ddfcebf77b2a109b/py/desitarget/mock/fluctuations.py) including some [simple tests](https://github.com/desihub/desitarget/blob/ed9a490f84ad6118225d3a60ddfcebf77b2a109b/py/desitarget/test/test_mock_fluctuations.py). 

You pass as input RA,Dec locations and get back the densities at those locations. The returned values are constant across bricks. 

Is this the kind of inputs/outputs/tests we want to implement?

**Comment by geordie666** [comment]
Looks reasonable...the "fluctuation factor" function that we'll use to
scatter the mock densities will come from the empirical data rather than
being a simple Gaussian and will be a function of empirical parameters that
can be chosen for the brick (E(B-V) etc.

**Comment by geordie666** [comment]
@forero...I still need to check my working over the weekend (so I'm not issuing a PR), but code to measure target density fluctuations in the real data now exists on desihub/desitarget (the branch is called "QA") and the output file from this code is on NERSC at:

~adamyers/brick-info-dr3.fits 

This is still preliminary, but it will give you a chance to see the information that will be available from the data side, if you want to play around with it.

**Comment by forero** [comment]
@geordie666 sounds good. I will continue integrating this structure into the mock subsampling assuming the inputs/outputs described in `density_across_brick`.

**Comment by sbailey** [comment]
Thanks for the file.  Taking a quick look, the densities max out at values way different from FDR expectations.  I suggest that we use this to make a fake model of density ratio vs. E(B-V) and depth, and what the random variance is about that model, while still pegging the absolute normalization to the desimodel/data/targets/targets.dat numbers (which should match the FDR, or possibly updates since then, but if anything in there is out of date we should update it there and not just hardcode it in these sims).

Is there a clean way to identify which bricks are "done" i.e. have full coverage to full depth?  Plotting density vs. RA,dec makes it clear that we have a large amount of partial regions and edge effects that could impact our interpretation (e.g. if a brick is 70% covered to full depth, it's median depth could look quite good while its density could be considerably different than what it would be if it was 100% covered to full depth).

**Comment by geordie666** [comment]
As depth is reported in the file, the cleanest way would be to choose our
preferred depth in each band and only consider bricks with "full" depth in
every band.

I could also add NEXP (number of exposures) to the file? But I think we
could just make a decision on what depth we're going to consider in each
band as "full enough"

**Comment by sbailey** [comment]
Yes, filtering for bricks that meet depth in all bands is a good first cleanup cut.

But if your DEPTH_* values are the median depth in the brick, it doesn't capture the edge effect of a brick that is >50% full depth while still having a significant fraction of non-full depth data that would affect the observed target density for that brick.  If your DEPTH_* values are average depth across the brick then it is less susceptible to this problem (but more susceptible to outliers...).

Suggestion:
* add NEXP as you suggest
* add depth percentiles, e.g. 10, 25, 50 (median), 75, 90th percentile of depth
  * `np.percentile(pixeldepth, [10,25,50,75,90])`
* add RMS of depth across the brick
(and all of those per band...)

**Comment by geordie666** [comment]
All good ideas, particularly the depth percentiles. Will try to add that
this weekend.

**Comment by geordie666** [comment]
I added the depth percentiles, at least (https://github.com/desihub/desitarget/commit/4f95489faa8a90dcfb7c9e1ad26a52b1497ea808) I'll see if I can get to anything else (NEXP etc.) before Tuesday (when I should probably switch over to thinking about the bright star mask).

**Comment by geordie666** [comment]
QA.py in the latest version of the QA (https://github.com/desihub/desitarget/tree/QA) branch:

https://github.com/desihub/desitarget/blob/2b9362d1a09a072e88ecc33b8ce1ec7a194a4909/py/desitarget/QA.py

Contains the modules _fluc_map_ and _quad_fit_ that could be used to generate a (quadratic) function fit to target density fluctuations (at the brick level) around the median target density. _fluc_map_ takes a "brick_info" file as input, which is available at NERSC ( ~adamyers/brick-info-dr3.fits). _fluc_map_ cuts on NEXP to recreate "3-pass imaging" (the requirement is to only use bricks that have achieved a median of 3-passes in all bands).

At this point, I need some guidance as to how to interface this with the mocks. I could produce quadratic fits to each of EBV, G_DEPTH (which is the weighted mean depth in G), R_DEPTH etc. Or, I could produce 2-D covariance fits (these would get noisy given that  a change of 1 target per brick is 4 targets per sq. deg.). Or, we could merge the current QA branch and @forero could call _QA.fluc_map_ and then _QA.quad_fit_ on the fly.

Guidance @sbailey @forero ?

**Comment by sbailey** [comment]
Caveat: I haven't mentally mapped how this related to @forero's 
[first try to generate mock density fluctuations](https://github.com/desihub/desitarget/blob/ed9a490f84ad6118225d3a60ddfcebf77b2a109b/py/desitarget/mock/fluctuations.py) mentioned in an earlier comment.

I suggest we use these QA functions to derive coefficients for a model that the mocks would use, but not have the mocks call these functions directly.  Thinking aloud for what we need:

1. a model of what *depth* fluctuations per brick to expect, e.g. a mean and sigma per band.
2. a model of *density* fluctuations vs. depth and E(B-V) for each target class.  This is also a mean and a sigma.  i.e. there is a random component of what the actual density would be, in addition to the mean density derived from the model fit to depth and E(B-V).

When building a mock target catalog, we would randomly assign depths to bricks based upon the model (1).  We would then use those depths as input to the model (2) to generate what density to use for each brick for each target class.  The targets themselves and the depth would get propagated to the target catalog; the actual true density used would be put in the truth file but not the targets file.

Detail: We could consider splitting these into two steps: generate the random depths and densities per brick and save that, and then use that as inputs for generating random realizations of targets at those densities.  Or we could do it all in a single step.  Two steps would be more of a hassle, while giving a little more freedom to separately study the various effects.

If this explanation doesn't make sense, perhaps @forero, @geordie666, and I could have a google hangout on Thursday to discuss options.

**Comment by geordie666** [comment]
This makes sense to me...if @forero agrees with these suggestions, I can code them up today...

**Comment by forero** [comment]
@geordie666  Makes sense to me.

**Comment by forero** [comment]
@geordie666 @sbailey 
Here is my try to generate EBV and DEPTHS using Adam's results
https://github.com/forero/SandboxDESI/blob/master/end2end/target_fluctuations/DR3_depth_estimates.ipynb

I am basically computing the integrated probability distribution for each quantity, finding (by hand!) 10 points to generate a decent interpolation of the inverse function of that integral and then generating a bunch on random numbers in [0,1] to get the corresponding values for EBV/DEPTHS. 

Does that sound reasonable to you?

**Comment by geordie666** [comment]
@forero: This looks reasonable but I have two comments:

(1) Unfortunately, I think that you also need to generate these for GALDEPTH_G, GALDEPTH_R and GALDEPTH_Z, too?
(2) The fraction < DEPTH_G plot makes sense to me, it says that < 10% of observations have DEPTH_G of < 24 (which is in agreement with the map I made). But, the final plot on the page seems to have more than 500 bricks with DEPTH_G < 24? Is that just my eye deceiving me because it's hard to see things with DEPTH_G ~ 24 in the plot?

(I'll work on the final piece of this, today)

**Comment by forero** [comment]
@geordie666 
(1) Good. 
(2) 12% of the generated points have DEPTH_G<24. This fraction is 10% in the data. I guess it's good enough.

**Comment by forero** [comment]
@geordie666 new iteration https://github.com/forero/SandboxDESI/blob/225d173b7ad3a1a66e037a1ca0a9ec7cc15b7668/end2end/target_fluctuations/DR3_depth_estimates.ipynb

I am modeling the differences between depth-galdepth as gaussians to generate galdepth from depth.

**Comment by geordie666** [comment]
@forero: Your new iteration looks good.

If you checkout the latest branch of QA, there is now a function that you can pass an array of brick values and obtain the target density fluctuations. It takes the same brick file that you're using in

https://github.com/forero/SandboxDESI/blob/225d173b7ad3a1a66e037a1ca0a9ec7cc15b7668/end2end/target_fluctuations/DR3_depth_estimates.ipynb

(bf = "../../data/brick-info-dr3.fits")

as one of the inputs.

If you've already generated an array of brick depths, then you would call this code as follows, for example:

from desitarget import QA
flucs = QA.generate_fluctuations(bf,"LRG","DEPTH_G",deptharray)

Here, you could substitute any of our target classes (e.g. QSO, ELG, ALL, etc.) for "LRG" and you could substitute any depth value for "DEPTH_G" (e.g. DEPTH_R, GALDEPTH_Z etc.). Note that you can also pass "EBV" in place of "DEPTH_G" and, if you did so, then deptharray should instead be a per-brick array of E(B-V) values rather than a per-brick array of depths.

The output is an array of per-brick target fluctuations (relative to the mean expectation from the FDR). I think we probably want to just multiply the per-brick fluctuations for E(B-V) together with those for each individual depth. Technically we'd want those different systematics to be covariant, but there aren't enough bricks to empirically explore those covariances across multiple systematics.

Another stretch goal is that the systematics should technically be correlated with position in the sky...but they won't be as you're currently generating the mocks!

Finally, I think I can speed the code up a little bit, but the current version in QA is mature enough for you to use.

**Comment by forero** [comment]
@geordie666 thanks! I will be able to test that tomorrow. Any suggestion on how to implement sptial correlations?

**Comment by dkirkby** [comment]
Do you want to mimic the observed spatial variations in the imaging, or generate a spatially correlated random field on the sky?

**Comment by geordie666** [comment]
@forero: I think the easiest way forward to produce meaningful spatial variations would be:

(1) For depths: Just call the depths randomly as we were already doing for my QA code
(2) For E(B-V) For the bricks that you're passing to my QA code, use real values of E(B-V) for the center of the brick and track which brick had which E(B-V) rather than passing random bricks

We could improve on (1) if I built a function of how depth depended on RA/Dec. But, we might just pass on that for now as the way obsbot works (the automated imaging planner) I'm not sure how spatial correlations would look. That might require a lot of further study. Or, I could try to implement something...

**Comment by forero** [comment]
@geordie666 I will use Dustin's suggestion to get the real values of E(B-V). @dkirkby I would like to generate a spatially correlated random field on the sky that statistically follows the depths' distribution in DR3. Even better if it manages to generate a model to extend DR3 depths to unobserved regions (i.e. something like this http://wwwmpa.mpa-garching.mpg.de/ift/nifty/gallery.html#d3po-light)

**Comment by moustakas** [comment]
I know this issue is long-closed, but can we also somehow add the typical variance of the *WISE* fluxes, as a function of brick?  I need this to properly add photometric noise to the mock galaxy / star photometry as part of #136.  Thanks.
