### ISSUE TITLE
full set of BGS flux cuts not implemented

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#114]
BGS has adopted two magnitude cuts for target selection, an r<19.5 high-priority (bright) sample and an 19.5<r<20 lower-priority (faint) sample, as documented [here](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1770).  However, only the bright cut is currently implemented in ```desitarget.cuts.isBGS```.   [Note: the documentation on the [targeting wiki page](https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection#BrightGalaxySurveyBGS) is currently out of date but will be updated imminently.]

These two samples each get a different targeting bit, although I'm not sure how to best implement the cuts, e.g., should there be separate ```isBGS_bright``` and ```isBGS_faint``` functions (ideally within a single Class as described in #37), or something different?  @sbailey @geordie666 please advise.

**Comment by geordie666** [comment]
@moustakas: As the bright and faint BGS targets are fully expected to be separate targets throughout DESI (rather than an experimental test of different target selections) I would supply them directly in cuts.py as two separate functions `isBGS_bright` and `isBGS_faint` exactly as you describe. The current defaults should be encoded in cuts.py.

As we've discussed the last few weeks, I'm moving away from the "single class" suggestion because I think cuts.py should only contain the currently implemented _default_ set of cuts (for simplicity, documentation etc.). Experimental cuts, I think, should be in a separate /sandbox directory that could be called as needed but wouldn't be confused with the current default cuts.

**Comment by forero** [comment]
I welcome the idea of having a separate set of experimental cuts. We are using our set of cuts in `mocks` (i.e. https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/selection.py#L160) but it would be great to have a standard place (different from `cuts.py`) to call them as needed.
