### ISSUE TITLE
refactor and expand targets_truth

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#136]
```mock.build.targets_truth``` needs to be refactored and expanded to include the metadata necessary to generate spectra.  This issue is directly related to https://github.com/desihub/desisim/issues/203.

I am also planning to address #133 and #130 here.

**Comment by moustakas** [comment]
I am refactoring ```mock.build.targets_truth``` to add identifying spectral information to each mock target.  This will slow things down but I think it's the behavior we want because doing the mapping will a more realistic set of metadata (```DECAM_FLUX```, ```OIIFLUX```, etc.) to each mock object that I think we still want, even if we're not generating spectra (i.e., even if we're just doing a "quicksurvey"-like, catalog to catalog data challenge).  In particular, this should address issues like #127 which right now are being handled in a very ad hoc way.

I'm asking in case this *isn't* the behavior we want.  @sbailey?  @forero?  @dkirkby?

**Comment by moustakas** [comment]
One more question: can I break backwards compatibility (=somewhat annoying)?  We can always use an (older) tagged version of the code if necessary, right?

**Comment by moustakas** [comment]
I decided that since the spectra are being generated anyway in ```mock.build.targets_truth``` (in order to be able to apply the target selection cuts correctly), we might as well write them out.  Any thoughts on what data model I should use to write these out?  I'm parallelizing by ```brickname```, so that's one option, although to use the ```simspec``` input to ```desisim.quickgen``` we actually want the spectra organized into *frames* (which would require a night and exposure ID).

Should I just write the spectra in bricks (across all the spectral classes) and just let the downstream steps (which, e.g., generate the fibermap files) deal with the reorganization?  @sbailey @forero?

**Comment by forero** [comment]
To me the spectra in bricks feels like the most convenient solution.

**Comment by moustakas** [comment]
@forero What are the *required* columns in ```targets.fits``` and ```truth.fits``` in order for ```quicksurvey``` to be run on the output of ```select_mock_targets```?

**Comment by forero** [comment]
In `targets`: TARGETID, RA, DEC, DESI_TARGET, BGS_TARGET, MWS_TARGET, SUBPRIORITY and OBSCONDITIONS. In 'truth': TARGETID, TRUEZ, TRUETYPE and SOURCETYPE.

**Comment by sbailey** [comment]
Replying to a question a few messages back:

> I decided that since the spectra are being generated anyway in mock.build.targets_truth (in order to be able to apply the target selection cuts correctly), we might as well write them out. Any thoughts on what data model I should use to write these out? I'm parallelizing by brickname, so that's one option, although to use the simspec input to desisim.quickgen we actually want the spectra organized into frames (which would require a night and exposure ID).
>
> Should I just write the spectra in bricks (across all the spectral classes) and just let the downstream steps (which, e.g., generate the fibermap files) deal with the reorganization? @sbailey @forero?

At the point of mock.build.targets_truth, writing out by brick is good, keeping just noiseless high resolution true flux vs. wavelength.  The simspec format isn't appropriate at this level, since it needs information about the observing conditions and throughput for a particular exposure to calculate the photons observed on the CCD.  The same true target (that you would be writing out) could appear multiple times in the simspec files for multiple observations under different conditions.

**Comment by moustakas** [comment]
TODO: Apply Galactic extinction to each spectrum, based on its celestial position.

**Comment by moustakas** [comment]
Quoting from earlier in this thread:
```In targets: TARGETID, RA, DEC, DESI_TARGET, BGS_TARGET, MWS_TARGET, SUBPRIORITY and OBSCONDITIONS. In truth: TARGETID, TRUEZ, TRUETYPE and SOURCETYPE.```

From the code, ```SOURCETYPE``` includes names like ```GALAXY```, ```STAR```, ```SKY```, etc.  @forero, can you remind me where/when downstream these designations are needed?

**Comment by moustakas** [comment]
@forero I also don't understand the mapping between ```target_name``` and ```obsconditions``` (see, e.g., https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/build.py#L448-L459 in the master branch).  Isn't this information encoded in the ```targetmask.yaml``` file?  In other words, once we know the targeting type, can't we assign one/all of the ```obsconditions``` bits in ```targetmask.yaml```?

**Comment by forero** [comment]
@moustakas Answering the first question: `GALAXY`, `STAR`, etc are needed in quickcat
https://github.com/desihub/desisim/blob/master/py/desisim/quickcat.py#L40

Answering your second question. The targeting type is used to determine the `obsconditions` bits to feed it directly as an input to `fiberassign`. We do it this way because `fiberassign` doesn't know anything about `targetmask.yaml` or targeting types, it only knows `priorities`, `subpriorities`, `obsconditions` and how many more observations are left for that target.

**Comment by moustakas** [comment]
@forero  ```quickcat``` seems to know about ```ELG```, ```LRG```, ```BGS```, ```QSO```, ```STAR```, and ```SKY```, but not ```GALAXY```.   In fact, the only place I can think of that uses ```GALAXY``` is redmonster.  Or am I not understanding something?

As for the second question, it might be easier to talk about this on a hangout call if you're available.

**Comment by moustakas** [comment]
@forero @sbailey Do we want to write out the ```targets``` and ```truth``` catalogs to the brick directories together with the corresponding spectra, or do we still want monolithic ```truth.fits``` and ```targets.fits``` files (first raised in #89).  What about ```sky.fits``` and ```stdstars.fits```?

For ```targets.fits``` and ```truth.fits``` at this stage, my guess is that nobody is going to be using these intermediate catalogs---these files will be used as inputs to the pixel- and 1D-level spectral simulations, and the Collaboration will use the outputs from *that* part of the pipeline. In other words, it probably doesn't matter too much what we do here, in ```mock.targets_truth```.

But the ```sky.fits``` and ```stdstar.fits``` files are used in fiber-assignment, which I'm less familiar with.

**Comment by forero** [comment]
@moustakas you are right about the scope of `SOURCETYPE:GALAXY`. As far as I remember, `SOURCETYPE` is part of `truth` because we want to grab that column and put it in the `zcat` file as if it were an output from redmonster.

Monolithic `sky.fits` and `stadstar.fits` are used by fiberassign and I prefer to keep it that way, unless somebody else volunteers to rewrite the input routines in fiberassign to build a single array from brick files.  

`targets` and `truth` are handled as single tables.  I feel that with a fast python function to reconstruct `targets` and `truth` from a bunch of smaller files it would be easy to keep things working without making many changes.

**Comment by sbailey** [comment]
* TRUETYPE = the answer that a redshift fitter should find (SPECTYPE), e.g. GALAXY because it may not distinguish between ELG vs. LRG vs. BGS 
* SOURCETYPE = what to simulate it as, e.g. ELG, LRG, BGS

**Comment by moustakas** [comment]
Isn't it the opposite of what you've written?

**Comment by sbailey** [comment]
I don't think so; I empirically derived which was which by looking at a truth.fits file.

This distinction has been a mess throughout the code, and it is quite possible that we have variables called "truetype" than have values like "LRG" or "ELG".  But I'm pretty sure that I got the fits filename columns correct.

**Comment by moustakas** [comment]
@sbailey @forero Should the random seed be an input to ```select_mock_targets``` (which is how I have it now) or should it be specified in the input ```.yaml``` file (e.g., ```mock_bright.yaml```)?

**Comment by sbailey** [comment]
Initial reaction: let's keep it as a parameter to `select_mock_targets` so that we can reuse `mock_bright.yaml` without having to edit it everytime.  The output should record what seed was used too (i.e. the seed to `select_mock_targets`, not just the per-target SEED column in the metadata table).

**Comment by moustakas** [comment]
Closed in #156.
