### ISSUE TITLE
some target selection cuts for MWS missing from cuts.py

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#139]
Several of the targeting bits for the MWS (including those for white dwarfs) are assigned in ```mock.selection``` but missing from ```cuts```, the latter of which contains all our "official" cuts.  We should only ever use ```cuts```, so we know we're applying the same target selection criteria everywhere, including on the mocks (where possible).

Any volunteers to rectify this injustice?  @forero @apcooper @geordie666?

**Comment by geordie666** [comment]
I'll try to get to this over the weekend, if nobody has time today.

**Comment by geordie666** [comment]
I started to look through the mocks code this morning. It seems like there "is no" set of selection criteria for the MWS MAIN or the MWS WD sample. In `mock.selection` information is drawn directly from the mock file as to whether something is a MWS or a WD. Presumably, in `desitarget.cuts` we will want the _actual selection cuts_ to apply to GAIA input files, rather than having an input file that simply has a list of positions with MWS or WD turned on or off. I dug around to find the MWS cuts and they aren't, e.g., at https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection. So, maybe we don't have the knowledge yet to put the MWS cuts into `desitarget.cuts`? Guidance @moustakas? Are there MWS cuts lying around?

Note, also, that the FSTD cuts appear to be applied (identically) in both `mock.selection` and `desitarget.cuts`. So, nothing new seems to be needed in `desitarget.cuts` and I'd suggest that people working on the mocks side of things edit the `mock.selection` module. All it would seem to require would be a call to `desitarget.cuts.isFSTD_colors` instead of the line

`select_color     = (gmr - grcolor)**2 + (rmz - rzcolor)**2 < colortol**2`

I don't want to break the formalism of @forero, though

**Comment by moustakas** [comment]
@geordie666 Thank you very much for reviewing the code.  I agree that the (F) standard-star selection can be done using existing code, and I've already implemented that change.

As for MWS, I'm hoping @apcooper @crockosi @callendeprieto can help us out.  Is it the case that for the full-survey data challenge we want the various samples to be selected *perfectly* from the mocks, or are there actual target selection cuts floating around I'm not aware of?  This is definitely an agenda item we should talk about at the next Targeting telecon.

**Comment by moustakas** [comment]
There was significant traffic on this question on-list and for the full-survey Data Challenge we've essentially confirmed (with the relevant Working Groups) that we will be using a 'perfect' selection of MWS targets based on the mocks themselves.  We should reopen an issue on this topic once we have Gaia/DR2 in hand.
