### ISSUE TITLE
choosing column names for the various "types" of sources

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#149]
Summarizing the current set of choices (discussed briefly in #136 and in an off-list conversation with @sbailey and @forero):

* `SOURCETYPE` -- template type used to generate the simulated spectrum (e.g., `BGS`, `STAR`, etc.) .  Used and needed by `desisim.quickcat` (although that code doesn't know about all the types we are handling in the mocks now, and will need to be updated).

* `TRUETYPE` -- a "lower resolution" version of `SOURCETYPE` which can take on one of four values: `GALAXY`, `QSO`, `STAR`, and `SKY`.  

* `SPECTYPE` -- the redshift-fitted (e.g., from redmonster) version of `TRUETYPE`.  (By analogy, the redshift `Z` can be compared with `TRUEZ` from the truth table.)

Besides being confusing (to me, at least!), these choices also don't accommodate subtypes, either in the truth catalogs or in the redshift-fitting output files.  For example, [redmonster](https://github.com/desihub/redmonster/blob/master/doc/redmonster-output-file.pdf) returns both `CLASS` -- which we rename `SPECTYPE` -- and `SUBCLASS` -- which we don't keep, but should (see last bullet below).

I propose we make the following changes:

* Adopt `TEMPLATETYPE` in lieu of ~~`SOURCETYPE`~~ -- This choice is clear and unambiguous. The possible values are currently: `BGS`, `ELG`, `LRG`, `QSO`, `STAR`, `WD` and `SKY`.

* Add `TEMPLATESUBTYPE` -- This is needed for the white dwarfs to differentiate between `DA` and `DB` types (see https://github.com/desihub/desisim/issues/200).  We could also choose to designate Lyman-alpha QSOs with a `LYA` subtype.

* Adopt `TRUESPECTYPE` in lieu of ~~`TRUETYPE`~~ -- This column name will make it clearer that this quantity should be compared against the fitted ```SPECTYPE```.  

* Add `TRUESPECSUBTYPE` -- This would be a new column which could include a rough spectral class for stars (e.g., based on a coarse mapping between temperature and log-g and spectral class and luminosity class, respectively) and, potentially, an approximate "star-forming" vs "passive" designation for galaxies (e.g., based on a physically motivated cut on D(4000), which we have for all the galaxy types).

* Finally, we should add `SPECSUBTYPE` as an additional output of the redshift-fitting code(s).

I realize that some of these column names are long and arguably clunky, but only at the expense of clarity and being self-documenting, which counts for a lot!  

Thoughts?

**Comment by sbailey** [comment]
* rename `SOURCETYPE` to `TEMPLATETYPE`: good
* add `TEMPLATESUBTYPE`: good
* rename `TRUETYPE` to `TRUESPECTYPE`: I'm more ambivalent about this, but appreciate the argument for clarity trumping brevity since people have been confused about this.  OK to rename.
* add `TRUESPECSUBTYPE`: the exact use of this is unclear to me.  Is it effectively degenerate with `TEMPLATETYPE` + `TEMPLATESUBTYPE`, and/or the metadata table from the generated spectra?  Who would use this and how, and is it expected to match up to the output of the redshift classification?
* add `SPECSUBTYPE`: we already have `SUBTYPE` defined in the zbest output, though you could make a clarity argument too that this should be `SPECSUBTYPE`.  We left this as an optional output of redshift fitters without defining what the valid values should be.  Redmonster `subclass` is a rather verbose string dump of a dictionary; earlier versions of desispec tried to stuff this into `SUBTYPE` but we ended up with truncated values like `{'EW_Halpha': 10.0,` and `{'stellar_type': 'F9` so we ended up turning it off (writing "NA") until we could clean this up.

Having a placeholder for `SUBTYPE` or `SPECSUBTYPE` in the redshift fitter output is good, but how formally do you think we should define the allowable values, and do you think they should be defined in a way that would exactly match the `TRUESPECSUBTYPE` if that is included?  Detailed `(TRUE)SPECSUBTYPE` is smelling like feature creep for a redshift fitter and is perhaps better framed in the context of additional science codes for measuring stellar, galactic, and QSO properties with datamodels that match their exact needs instead of trying to shoehorn everything into a single short character string.

**Comment by moustakas** [comment]
All great comments, thank you.  For now I will incorporate/adopt `TEMPLATETYPE`, `TEMPLATESUBTYPE`, and `TRUESPECTYPE` and leave off the rest of the tags/columns to be discussed and dealt with on the (output) redshift-fitting side if necessary.  

And I agree that here (i.e., in the mock code) `TRUESPECSUBTYPE` is both ill-defined and not on the critical path.

**Comment by moustakas** [comment]
Closed in #156.
