### ISSUE TITLE
Package dependencies in desitarget

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#15]
I'm trying to determine exactly which packages need to be installed in order for Travis tests of desitarget to run successfully, so here are some questions about the packages:

1. desitarget appears to use both astropy.io.fits and fitsio for reading FITS files.  It should only be astropy.io.fits, unless there is an overriding, very good reason to use fitsio.  They are even both used *in the same file*!
2. I see that there is a dependency on h5py.  That's not necessarily a problem, but at this stage it is worth asking whether the Durham mocks will always use this format.

**Comment by sbailey** [comment]
We originally tried using only astopy.io.fits but due to [insurmountable bugs](https://github.com/astropy/astropy/issues/4233) and poor performance of astropy.io.fits, it really is important to use fitsio instead for this case.  The leftover astropy.io.fits is due to portions that weren't fully ported.  We hadn't worried about those because our standard installs have astropy already, but I can understand if you'd prefer to keep a package entirely one or the other so that you don't have to install both on-the-fly for Travis testing.

I think the Durham mocks will always be in hdf5.  The "import hdf5" should be isolated so that if you aren't using Durham mocks you can use the rest of the code without needing h5py.  If that isn't the case, we should fix that.

**Comment by weaverba137** [comment]
It's fine to use fitsio then, but at the very least, you should not be using astropy.io.fits anywhere.  If you need other aspects of astropy, that's OK.  It's just really, really confusing that both FITS readers are being used in the same file.

**Comment by weaverba137** [comment]
So who is assigned to removing astropy.io.fits.  Is someone else working on that already?

**Comment by rainwoodman** [comment]
I will do it.

**Comment by sbailey** [comment]
Current status:
  * h5py is isolated in the durham mock reader; if you don't read those files, you don't need h5py installed
  * fitsio is the standard FITS reader for desitarget because of much better performance when spinning over the tractor/sweep files.
  * some references to astropy.io.fits still exist as part of ensuring that data read using that library can still be used with the algorithms.

Closing this issue.
