### ISSUE TITLE
include DECAM_NOBS and/or DECAM_(GAL)DEPTH in targets catalog?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#151]
Right now `select_targets` does not write out information on the depth of the observations at the position of each target.  It would be very useful to have this information both for QA (see #21) and for identifying reliable targets (e.g., those in 2-pass imaging).

The columns currently being written out are hard-coded in `desitarget.io` to be:
```
tscolumns = [
    'BRICKID', 'BRICKNAME', 'OBJID', 'TYPE',
    'RA', 'RA_IVAR', 'DEC', 'DEC_IVAR',
    'DECAM_FLUX', 'DECAM_MW_TRANSMISSION',
    'DECAM_FRACFLUX', 'DECAM_FLUX_IVAR',
    'WISE_FLUX', 'WISE_MW_TRANSMISSION',
    'WISE_FLUX_IVAR',
    'SHAPEDEV_R', 'SHAPEEXP_R','DCHISQ',
    ]
```
(What's surprising is that I thought we wanted the inverse variances in the shapes as well...)

@geordie666 @sbailey What do you think?

**Comment by geordie666** [comment]
I think we have to be careful about the purpose of the targets file.

Philosophically, it should include everything we need to assign target bits
and nothing more. Things that are useful for science analyses should be
matched back to the targets file after-the-event...because, the list of
useful things that people would like in the targets file will continue to
grow (by the end of SDSS we were creating a "standard" file with over 200
columns!)

On the other hand, the target files aren't prohibitively large yet (in an
I/O limiting sense), so if there's a good target-assigning-bit reason for
including the depths in the target files (if those depths are available
somewhere) I wouldn't be opposed to that.

**Comment by moustakas** [comment]
Thanks, @geordie666, I agree we need to be sure that this particular output file doesn't grow without bound, but---at least for now, while the imaging surveys are still ongoing---it's very important to have this depth/nobs information handy.   Thanks for merging #152; closing this issue now but if others want to chime in please reopen.
