### ISSUE TITLE
propagate pre-calculated healpix pixel number

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#238]
Filing under desitarget because this is where it starts, but this is a cross repo ticket.  From @weaverba137 in desihub/two_percent_DESI#6:

> If healpix ids are known at the time of fiberassignment, it would be good to include those. It would possibly simplify some joins.

Target selection calculates this and outputs as HPXPIXEL column.  This should be propagated through fiber assignment, fibermap files, expanded fibermap tables in spectra files, and included in the output zcatalog table.

Currently we recalculate the healpixel ID from RA,dec at multiple steps.  This is reproducible as long as we stay within python and healpy, but it could become problematic if we ever branch beyond that and use a different healpix library that may have edge effect differences (AFAICT the healpix standard doesn't define which pixel an (RA,dec) belongs to if it lands *exactly* on a pixel boundary or corner).

**Comment by moustakas** [comment]
I propose we close this issue, since it's not really for desitarget.  I created specific issues in 
https://github.com/desihub/desisim/issues/410 and 
https://github.com/desihub/fiberassign/issues/96#issuecomment-419440227 so we can track this there.  

We probably also need an issue in `redrock` (or `desispec`?), to ensure the (same) healpixel number gets all the way to the end.
