### ISSUE TITLE
should obsconditions be in mock targets catalog or not?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#253]
@forero In #207 (see especially https://github.com/desihub/desitarget/pull/207#issuecomment-321052091) after some discussion it was decided to *not* include `OBSCONDITIONS` in the mock targets catalog, since this is something that should be computed by the MTL on the fly.  

However, in https://github.com/desihub/desitarget/pull/211/commits/83627e28249e611f8319489bf567732240ef156a and https://github.com/desihub/desitarget/pull/211/commits/f43aa0e9f1d69a0f7cacca3b965cf1ccd4bc9a15 you added this back in.  (Mea culpa that I didn't ask this question sooner, since I was the reviewer on that PR!)

Perhaps @sbailey can weigh in as well, but should `OBSCONDITIONS` be in there or no?

**Comment by moustakas** [comment]
Following up on this question.  @sbailey do you know, offhand?

**Comment by sbailey** [comment]
Thanks for the reminder.

OBSCONDITIONS is a bitmask of allowable observing conditions for a given target, which should be completely derivable from the targeting bits themselves.  Having it in the targeting table itself may seem convenient, but it would be better to *not* have it in the table and provide utility functions instead, in case we change our mind about which bits are allowable under what conditions (then we just update targets.yaml instead of having to release a new targeting catalog just to update that column).  e.g.
```python
def get_obsconditions(desi_target):
    '''returns obsconditions mask for input array of desi_target targeting bits

    desi_target can be int or array-like; return value matches dimensionality
    '''
    ...

def ok_obsconditions(desi_target, conditions_mask):
    '''check whether desi_target can be observed under conditions_mask

    conditions_mask is int; desi_target can be int or array-like;
    return value matches dimensionality of desi_target
    '''
    ...
```
(or a better name than `ok_obsconditions`...)

**Comment by moustakas** [comment]
It was decided in #264 to not include `obsconditions` in the output (mock) target catalogs, so I'm closing this.
