### ISSUE TITLE
Refactor desitarget.cuts.apply_cuts to deal with individual spectral classes

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#26]
Refactoring desitarget.cuts.apply_cuts so that the nominal target-selection cuts can be applied to individual spectral classes would be very helpful for developing / testing target selection and for the templates work (in desisim).

**Comment by sbailey** [comment]
+1 on this.  I suggest that `apply_cuts` still take the tables from tractor/sweep files as it currently does, calculates the extinction corrected fluxes as needed, and then call functions that explicitly take the variables that they need to make the cuts for each target class, e.g.`isELG(gflux, rflux, zflux)` rather than `isELG(objects)`.  These would return a boolean array that is the same length as the inputs, and `apply_cuts` would be the thing that assembles those back together into the target bitmasks.

**Comment by moustakas** [comment]
@rainwoodman Would it be possible for you to tackle this refactoring? If not, no problem -- thanks!

**Comment by rainwoodman** [comment]
No problem. I will file a PR on this along the lines Stephen suggested.

Yu

**Comment by sbailey** [comment]
Thanks @rainwoodman for implementing this in PR #27 which is now merged.  The remaining piece is standard stars, which would have a messy function something like
```
def isStdStar(gflux, rflux, zflux, givar, rivar, zivar, gfracflux, rfracflux, zfracflux, psftype):
    ...
```
Is that what we want?  Other ideas?

**Comment by moustakas** [comment]
We can reopen this if additional refactoring is needed in the future.
