### ISSUE TITLE
dc17b: discrete input high z qso

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#260]
Carried over from https://github.com/desihub/desisim/issues/308 as reported by @ngbusca.

In dc17b, the input redshifts for high z quasar (above ~1.7) are discrete. Here's a plot of z_fit vs. z_input with a zoom at the transition redshift.

![image](https://user-images.githubusercontent.com/1431820/34919372-b512615a-f930-11e7-8f47-75147718ee74.png)

**Comment by sbailey** [comment]
This problem is still present in the 17.12 reference run /project/projectdirs/desi/datachallenge/reference_runs/17.12/targets/truth.fits, which used the QSO mocks /global/cscratch1/sd/ioannis/desi/mocks/GaussianRandomField/v0.0.5/QSO.fits, which do *not* have this binning.  It also used /global/cscratch1/sd/ioannis/desi/mocks/lya_forest/v0.0.2/metadata-simpleSpec.fits for LyA mocks, but that starts at 2.1 (or so says the select-mock-targets.yaml file).  i.e. it appears that we are introducing this in the code, not in the mocks.  (!)
