### ISSUE TITLE
Target density plots for mock QA appear to be broken

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#265]
See, e.g., the top plot at:

http://portal.nersc.gov/project/cosmo/temp/ioannis/refactor/LRG.html

where the target density 2-D map and histogram don't have much coverage

**Comment by moustakas** [comment]
I think this is because I only mocked up one nside=32 healpixel -- with more data these should become more populated and visible.  See, e.g., http://portal.nersc.gov/project/cosmo/temp/ioannis/mockqa/LRG.html, which is the same code but using the (old) dc17b data.

But I agree that it would be nice for these plots to be(come) more useful when passing a small patch of sky.

**Comment by geordie666** [comment]
Ah, let's just close this one, then.
