### ISSUE TITLE
new better-than-random sky target density high enough?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#280]
Previously (when using `$DESI_DATA/mocks/GaussianRandomField/v0.0.1/2048/random.fits`) we were aiming for a sky target density of 1400/deg2. However, with `$DESI_DATA/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits` (see #219) I estimate a target density of 1220/deg2.  

Is this new, lower density sufficient for fiber assignment?

**Comment by sbailey** [comment]
The intension is that sky densities should be in terms of N per positioner patrol area rather than N per square degree with Poisson fluctuations resulting in some positioners undercovered and others over covered.  I had thought that 2 per positioner would be sufficient but desihub/desitarget#100 indicates that this may not be sufficient.  We need to track down those specific cases to confirm why not and what density is sufficient.  See #219 for a plot of how the lower-but-not-Poisson density results in more fibers covered by a sky target.

The final proof is whatever skies are produced in real data should be dense enough that there is always a target for every positioner unless it really is impossible (e.g. a gap in the imaging data).

It would be ok if `select_mock_targets` doesn't downsample at all, and just let is pass forward whatever is in the mock.

**Comment by moustakas** [comment]
OK, easy enough.
