### ISSUE TITLE
Tune contaminant densities

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#285]
Ironically, after 120+ commits, the "fix-densities" branch didn't tune the contaminant densities; see PR #264 :) .  Study and tune those densities.  The most egregious case is stellar contamination of BGS targets.

**Comment by moustakas** [comment]
For the record -- and in my defense! -- the `fix-densities` branch was so named to fix the too-low QSO+Lya target densities (originally started in #192 in June 2017), which we did.  Tuning contaminant densities have always been problematic because of inadequacies of our mocks (although the Buzzard mocks -- see #249 -- should help address this issue).  Finally, the refactor in #264 was designed to much more easily accommodate including contaminants and other desired improvements and features.

**Comment by moustakas** [comment]
The Lya working group has started collecting some very useful notes and ideas for simulating QSO contaminants, which I'm linking here for reference---
  https://desi.lbl.gov/trac/wiki/LymanAlphaWG/SimulateQuasarTargets

**Comment by moustakas** [comment]
Now tracking this issue in #401; closing this one.
