### ISSUE TITLE
Missing GMM files

### ISSUE THREAD

**Issue by julienguy** [desihub/desitarget#303]
In desitarget/py/desitarget/mock/mockmaker.py 
GaussianMixtureModel.load(gmmfile)
with 
 gmmfile = resource_filename('desitarget', 'mock/data/lrg_gmm.fits')
  gmmfile = resource_filename('desitarget', 'mock/data/elg_gmm.fits')
 gmmfile = resource_filename('desitarget', 'mock/data/bgs_gmm.fits')

none of those file is in the repo.

**Comment by sbailey** [comment]
This is a leftover bug from PR #300 where those files were moved into `mock/data/dr2/*_gmm.fits` instead of `mock/data/*_gmm.fits`.

Consider using the `mock/data/dr5/colors/*_gmm.fits` files which include more parameters in the GMMs (I haven't personally looked into the details, but something trained on DR5 sounds better than something trained on DR2...)

**Comment by julienguy** [comment]
Code fails with mock/data/dr5/colors/*_gmm.fits , running with mock/data/dr2/*_gmm.fits .
I am waiting to see if it finished correctly on one healpix and will directly push the fix to master.

**Comment by julienguy** [comment]
fix pushed in master
