### ISSUE TITLE
tiny GFA file

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#330]
An older version of `gfas-dr6.fits` had 18M sources. The latest version (last modified yesterday afternoon) only has 46K sources. Why is that?

**Comment by geordie666** [comment]
That's because I changed the GFA generation code, but as Cori was down late last week I hadn't yet had a chance to run things over the whole sky again. The current file only has a couple of bricks I ran for testing. Apologies for not using a new file name...I'll run the code again now and the new file should exist at that location in under an hour.
