### ISSUE TITLE
add FIBERFLUX columns to mock targets catalog

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#375]
Related to #369, the `targets.fits` files generated by `select_mock_targets` needs to add the `FIBERFLUX_[GRZ]` and `FIBERTOTFLUX_[GRZ]` columns needed by fiberassignment.  

@dkirkby is't there code (e.g., in `specsim`) to estimate these quantities from a given surface brightness profile, ellipticity, and size?  If so, can you point me to the code here?

For reference `FIBERASSIGN_X` is defined as the "band flux within a fiber from this object in 1 arcsec Gaussian seeing" (see [here](http://legacysurvey.org/dr7/files).

**Comment by sbailey** [comment]
This is now a blocking factor because fiberassign master requires these columns (albeit for propagation only) but select_mock_targets isn't generating them.


@moustakas the relevant code is in `specsim.fiberloss.calculate_fiber_acceptance_fraction`, using the "fastsim" method so that we don't require galsim.  Trace downwards from `desisim.simexp.simulate_spectra` for an example that uses "fastsim", but there should be a way to directly call `calculate_fiber_acceptance_fraction` without going through the full spectral simulation.  @julienguy provided the "fastsim" method and may have a simpler example of how to use it.  See desihub/specsim#78 .

Related: This notebook fiberloss calculations for the "galsim" method:

https://github.com/desihub/specsim/blob/master/docs/nb/FiberlossExamples.ipynb

it calls https://github.com/desihub/specsim/blob/master/specsim/quickfiberloss.py .  It looks like the calling sequence for "fastsim" is different enough than for "galsim" that I'm not sure how useful those will be.

Even typical/median values as a fixed ratio from `FLUX_[GRZ]` for each target type would be helpful for moving forwards in the meantime.

**Comment by julienguy** [comment]
```
FastFiberAcceptance.value(self, source, sigmas, offsets, hlradii=None)

returns the fiber acceptance for the given source,sigmas,offsets

Args:
    source (string) : POINT, DISK or BULGE for point source, exponential profile or De Vaucouleurs profile
    sigmas (np.array) : arbitrary shape, values of sigmas in um for the PSF due to atmosphere and telescope blur
    offsets (np.array) : same shape as sigmas, values of offsets on focal surface between fiber and source, in um

Optional:
    hlradii (np.array) : same shape as sigmas, half light radius in arcsec for source

Returns np.array with same shape as input
```

Example

```
import numpy as np
import os
from specsim.fastfiberacceptance import FastFiberAcceptance

ntargets=10
plate_scale_arcsec2um=107.0/1.52 # um/arcsec, approximate, from DESIMODEL/data/desi.yaml
sigma_um=1.1/2.35*np.ones(ntargets)*plate_scale_arcsec2um # um
offset_um=1.*np.ones(ntargets) # um, fiber offset
half_light_radius_arcsec=np.linspace(0.2,1.5,ntargets) # arcsec (stays in arcsec)
for source in ["POINT","DISK","BULGE"] :
    acceptance = ffa.value(source,sigma_um,offset_um,hlradii=half_light_radius_arcsec)
    plt.plot(half_light_radius_arcsec,acceptance,label=source)

```
```

```
![figure_1-6](https://user-images.githubusercontent.com/5192160/45640137-a7d53b00-ba66-11e8-80eb-78dee3107ef7.png)

**Comment by moustakas** [comment]
At what wavelength is the fiber acceptance computed/returned?

**Comment by julienguy** [comment]
The wavelength dependence of the fiber acceptance comes from the variations of the input sigma,offset,half-light radius with wavelength. So for the purpose of the mock targets catalog, you should take the values of sigma and half-light radii at the central wavelength of the imaging pass-bands (we can ignore the second order variation of the effective wavelength with the spectral shape here).

**Comment by dkirkby** [comment]
This notebook has examples of using both the "galsim" and "fastsim" methods, and compares them:

  https://github.com/desihub/specsim/blob/master/docs/nb/SimulationExamples.ipynb

**Comment by moustakas** [comment]
Done in #381.
