### ISSUE TITLE
Revisit priorities

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#412]
Currently, `BAD_SKY` and `DONOTOBSERVE` both have a priority of `0`. Better would be to reserve `DONOTOBSERVE` to be exactly `0` and `BAD_SKY` to be `1`. We also need to reserve a low number for back-up filler targets for gaps and holes. Say `5`. This would then bump `DONE` and `OBS` to, say, `11` and `10`. I'll revisit this when I create the back-up filler targets.

**Comment by sbailey** [comment]
Bringing over my text from duplicate #413:

Review the priorities of the lowest priority targets to make sure we have an appropriate filler plan. Straw man suggestion from lowest to highest priority:

* 0: do not observe (e.g. to purposefully exclude a standard target that turned out to be bad)
* 1: BAD_SKY, targets of last resort (currently 0 in targetmask.yaml, but should be higher)
* 2-9: filler targets of some scientific interest
* 10: previously observed targets that are done, but we'd rather get another spectrum than waste it on BAD_SKY locations
* 11-999: other filler targets of some scientific interest; secondary programs
* 1000+: core DESI science program targets

**Comment by geordie666** [comment]
We implemented something _quite_ similar to Stephen's suggestion in the end, although the filler targets are actually in the range 10-100.
