### ISSUE TITLE
Tuning BAD_SKY criteria

### ISSUE THREAD

**Issue by Srheft** [desihub/desitarget#454]
@geordie666 et al.:

Looking at skies that are not flagged as BAD_SKY in  **/desi/target/catalogs/dr7.1/0.27.0/skies-dr7.1-0.27.0.fits**: 
for instance in the small chunk of 180<RA<186, 3<DEC<9:
`skies = fitsio.read('skies-dr7.1-0.27.0.fits', ext=1)`   
`inchunk=(skies['RA']<186) & (skies['RA']>180) & (skies['DEC']<9) & (skies['DEC']>3)`  
 `inskies =skies[inchunk]`
`is_bad_sky = inskies["DESI_TARGET"] & desi_mask["BAD_SKY"] != 0`
 `bad_sky =inskies[is_bad_sky]`
`print(len(bad_sky))`
`0`
`sAPFLUX_R = np.asarray([i[0] for i in inskies['APFLUX_R']]) ;swrf = np.where(sAPFLUX_R > 0.)[0] ; sFLUX_R =sAPFLUX_R[swrf]`
`sr_mag = [22.5-2.5*log10(sFLUX_R[i]) for i in range(len(sFLUX_R))]`
`snr,bins, srpatches = plt.hist(sr_mag, bins=bins, facecolor='red', alpha=0.6)`

 Some SKY targets have bright r-band magnitudes(used their first aperture flux),
![image](https://user-images.githubusercontent.com/32471902/52015070-58842a00-249e-11e9-8d6a-98956ee5bdea.png)

 And g, z mags in this particular case 
![image](https://user-images.githubusercontent.com/32471902/52011465-4b167200-2495-11e9-9d6b-97019af85c71.png)

The sky position in the bin of mag<20 is  shown below (180.22464412, 6.62003698):

![image](https://user-images.githubusercontent.com/32471902/52012426-c37e3280-2497-11e9-96a6-a58bf4d13009.png)

Unless there is a reason to observe these skies (@sbailey @julienguy @kdawson1000 : please comment if necessary), we request that the SKY selection algorithm be updated to either exclude these targets (maybe sticking to r-mag>22?) or mark them as BAD_SKY instead.

**Comment by geordie666** [comment]
@Srheft: The flux that determines a `BADSKY` target is currently completely arbitrary. I've been waiting for experts on sky subtraction to tell me what would be a good value. 

It's a one-line change to the code update the (default) value that delineates `SKY` from `BADSKY`. But, yes, in the current version of the code, the difference between `BADSKY` and `SKY` is completely meaningless.

**Comment by geordie666** [comment]
For the record: The line that changes this default is here:

https://github.com/desihub/desitarget/blob/master/bin/select_skies#L38-L40

**Comment by geordie666** [comment]
Based on a discussion with @julienguy, @Srheft, @kdawson1000 and @sbailey that we just had on a Data Systems telecon, I'll reset `BADSKY` to default to sky locations with `r > 25 OR g > 25`

**Comment by julienguy** [comment]
We want to do sky subtraction at better than 1% ,  a requirement is that we must not have stellar light contamination at a level higher than 1% of the dark sky flux.
The DESI dark sky model has a DECAM- G and R mags of 21.4/arcsec2 and 20.6 / arcsec2  .

So the stellar surface flux should  be fainter than 26.4 and 25.6 / arcsec2 in G and R.

**Comment by geordie666** [comment]
And I just realized that I have my greater than/less then criteria inverted. A `BADSKY` would be `r < 25 OR g < 25`. I shouldn't think in flux space!

I will update for the pure  `r < 25 OR g < 25` numbers for now. I'm guessing that the exact numbers are something that we need to establish in commissioning, but it's an easy change to the code when we know the empirical numbers.

**Comment by moustakas** [comment]
Echoing the numbers @julienguy quoted, I think these cuts should be defined on surface brightness.  , @geordie666 measures the "sky" flux in a couple different apertures (see, e.g., [this notebook](https://github.com/desihub/desitarget/blob/master/doc/nb/skies-dr7.1.ipynb)); if necessary, we could demand that `BADSKY` locations (or `SKY` locations for that matter) be defined based on the surface brightness in *both* apertures.

**Comment by Srheft** [comment]
I think Adam's proposal is in line with John's suggestion.  BADSKY defined by r<25 OR g<25 is equivalent to SKY defined by r>25 AND g>25.  These are effectively surface brightness estimates, as they are the magnitudes within a fixed aperture.  My estimates over the phone were g=22 in dark sky, which is somewhat darker than what Julien is reporting in the sky model.  So the x<25 criteria are going to be somewhat more conservative, which I think is okay.

Do we also want to flip a flag for BAD sky targets that lie within a certain distance of a bright star?  I would think yes, but that assumption depends on whether the sky fluxes are determined with or without background subtraction.  How are those fluxes determined?

**Comment by geordie666** [comment]
@Srheft: I don't see how an additional flag indicating that we are withing a certain distance of a bright star is informative. The purpose of `BADSKY` itself is to indicate that we are on the flux profile of a bright _something_, so an additional flag seems redundant.

@moustakas: I'm happy to divide all of the fluxes by the aperture area and report fluxes per sq. arcsec. instead of total flux in the aperture. Unless I'm missing something, though (which is entirely possible) that's equivalent to multiplying the flux threshold that defines `BADSKY` by the aperture area, which just seems like a cosmetic choice. I'm happy to do it either way, though.

**Comment by julienguy** [comment]
"So the x<25 criteria are going to be somewhat more conservative, which I think is okay."
This is not more conservative that the numbers I have suggested above. 

Repeating myself, 1% of the dark sky surface brightness (or flux in an aperture) seems to me a reasonable threshold. We would not be able to fit and subtract a sky model at a precision better than 1% (which is important to get for redshift fitting) with a stellar light contamination sky fibers larger than 1%.

**Comment by geordie666** [comment]
@julienguy: OK, to prevent further repetition I will rewrite the skies code to work in surface brightness units and use your supplied stellar surface flux thresholds of 26.4 and 25.6 / arcsec2 in g and r. I still hope that we'll check those numbers empirically during commissioning, though.

**Comment by kdawson1000** [comment]
Hmm, I just want to remind that the units in the original sky flux measurements were computed over a 1.5 arcsecond radius aperture, effectively six sq arcseconds.  So the x<25 criteria suggested by Adam is more conservative (is at a fainter limit) than 26.4/25.6 mag per sq arcsecond.  I don't mind using a brighter cut of 26.4/25.6 mag per sq arcsecond, but I just want to make sure that we are on the same page in terms of units.  I also thought this was just a cosmetic choice, but going to a classic definition of surface brightness should clear up this confusion.

As for the additional flag for nearby stars:  I just don't know how the skies are computed.  Are they background subtracted or are they computed directly from the raw images?  If they are background subtracted, then there may be some poor background modeling around the bright stars and we should flag those as BAD for the same reason that we flag science targets.  If they are not background-subtracted, then I agree with Adam that the flux will flood the aperture and trigger the BADSKY condition.

**Comment by moustakas** [comment]
> Hmm, I just want to remind that the units in the original sky flux measurements were computed over a 1.5 arcsecond radius aperture, effectively six sq arcseconds. So the x<25 criteria suggested

Remember that the DESI fibers are 1.5 arcsec in *diameter*, not radius.

**Comment by kdawson1000** [comment]
damn.  Although I thought that the units of sky fluxes were purely cosmetic, my participation in this discussion proves that it would be simpler to use the traditional surface brightness units of magnitudes per square arcsecond.

As for background subtraction:  given that the sky fluxes are systematically positive and seem to be distributed around reasonable sky levels for dark skies, these must be computed from the raw images and not background subtracted.  Am I right?  Assuming this is the case, then I agree with Adam that there is no need to apply a separate bright star mask.

**Comment by geordie666** [comment]
@kdawson: I _think_ that there is no background subtraction for the fluxes we extract in the sky apertures. The imaging files we are using for the skies are the Legacy Survey [image stacks](http://www.legacysurvey.org/dr7/files/#image-stacks), e.g.
coadd/<AAA>/<brick>/legacysurvey-<brick>-image-<filter>.fits

Perhaps @dstndstn could quickly comment for sure that these stacks have no special background-subtraction that would remove flux near bright stars?

Note also that the apertures stored in the skies files are _radius_ not diameter (see, e.g., HDU1 of [the data model](https://github.com/desihub/desidatamodel/blob/master/doc/DESI_TARGET/skies.rst). So the 0.75" aperture (`AP0`) in the current set of skies files corresponds to the 1.5" diameter DESI fiber.

In any case, at some point this week I'll update the code to report and apply measurements of magnitudes per square arcsecond instead of total flux.

**Comment by dstndstn** [comment]
The coadd/.../legacysurvey-BRICK-image-FILTER.fits files *do* have per-CCD sky subtraction with the "splinesky" models.  These do over-subtract the sky around bright stars, large galaxies, etc.  I would have expected the sky values to scatter around zero away from bright stars.  Near bright stars, I don't know if I would predict them to be systematically brighter or fainter -- probably both because the sky model will be unsuccessfully trying to remove the (unmasked portion) of the stellar halos--, but certainly they'd be *worse*.

**Comment by kdawson1000** [comment]
so, what do these sky fluxes mean then?

**Comment by dstndstn** [comment]
the sky fiber locations are selected to be as far from sources as we can get them, so they're basically a measurement of the unresolved background light (where the background models are trying to push that to an average of zero on large scales).  I think.

**Comment by djschlegel** [comment]
I had thought we were only differentiating between SKY and BADSKY based upon whether one is in a bright star or large galaxy masked region.  Note that roughly half of the SKY targets have positive and half have negative fluxes, as expected.  I donn't think we should be making any additional cuts (beyond not being inside a blob region), since if one too severely limits the sky selection to be in especially dark regions, we'll skew the spectroscopic sky modeling low.  (Julien has some nice work showing this for faint supernova spectra.)

<img width="580" alt="screen shot 2019-02-13 at 9 49 41 am" src="https://user-images.githubusercontent.com/7918018/52732494-3a75f980-2f75-11e9-9317-6b9229a3d79f.png">

Note that the distribution of sky values is pretty much a normal distribution for the APFLUX values in the SKY fibers, plotted below, corresponding to an RMS of 26.9, 26.3, 25.2 in g,r,z.  We don't seem to have the APFLUX_IVAR values in these target files though??

**Comment by geordie666** [comment]
We generate the distance from the nearest blob (`BLOBDIST`) as part of the skies code. So, I _could_:

- Include `APFLUX_IVAR` as an output in the skies files.
- Include `BLOBDIST` as an output in the skies files.
- Use the simple criterion `BLOBDIST==0` (plus the existing "not in a Legacy Surveys CCD footprint" criteriton) to set `BADSKY`.

@djschlegel: Does that seem reasonable?

**Comment by geordie666** [comment]
Oh, note that the `APFLUX_IVARs` _are_ already in the skies files (e.g.: `/project/projectdirs/desi/target/catalogs/dr7.1/0.27.0/skies-dr7.1-0.27.0.fits` at NERSC; the columns are named `APFLUX_IVAR_G`, `APFLUX_IVAR_R`, etc.). So, my above list would reduce to:

- Include `BLOBDIST` as an output in the skies files.
- Use the simple criterion `BLOBDIST==0` (plus the existing "not in a Legacy Surveys CCD footprint" criteriton) to set `BADSKY`.
