### ISSUE TITLE
Should unobserved quasar targets have higher priority than Lyman-alpha quasars?

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#486]
Documenting a conversation with Daniel Eisenstein, @nathalieGit and @sbailey at a targeting workshop. Patching in @andreufont for an opinion.

Currently, an unobserved quasar has lower priority than a Lyman-alpha quasar:

https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml#L166

This will mean that for close pairs of Lyman-alpha quasars one of the pair of quasars will *never* be observed, unless we happen to have more than 4 passes in a region with a pair.

Is this the desired behavior?

A simple change would be to instead give an unobserved quasar a *higher* priority than a Lyman-alpha quasar. This would mean that for close pairs, one quasar would be observed and if it's a Lyman-alpha quasar then the *other* quasar would be observed. If the *other* quasar is a Lyman-alpha quasar then it would receive 3 more observations.

So, the trade-off is that, if we make the proposed simple change then we would recover more close pairs of quasars with 3+1 observations instead of 4+0 observations. Behavior would be unaffected where there are no pairs of quasar targets within the fiber patrol radius.

**Comment by geordie666** [comment]
Note: I appreciate that ultimately the Lyman-alpha working group may give us a more complex schema for prioritizing quasars. But, this simple change would ensure, at least, 3+1 instead of 4+0.

**Comment by andreufont** [comment]
Hi @geordie666 - We had a similar discussion with Kyle in an e-mail exchange back in August, I copy paste it here. I don't think we ever finished the discussion, probably good to get it started again.

On 14 August 2018 at 22:41, Kyle Dawson <kdawson@astro.utah.edu> wrote:

    Hello all, particularly clustering and lyman alpha folks,

    We have several conditions on fiber collisions that we need to address in the fiber 
    assignment code. We need input from you to decide which object to give a fiber in 
    the case that two high priority objects compete for the same fiber and we already 
    have some information from prior observations. The obvious cases are:

    (a) two quasar targets, one is confirmed z>2.1 with only one epoch and the other 
    has not been observed.  Do we choose deeper observations of the known z>2.1 
    quasar or do we choose to increase sample size by taking an epoch of the unknown 
    quasar target?  
    ***PROPOSAL:  assign fiber to the known quasar.  
    LOGIC:  the second target has <20% likelihood of being a z>2.1 QSO, so spend the 
    time collecting data on the sure thing

While I agree with this logic, it is also true that close quasar pairs are also quite interesting, 
and that the difference between having 3 or 4 passes for a Lyman alpha quasar is not that big. 
May be we could decide to observe the other target once you have 2 passes of the Lyman 
alpha quasar. This way, if the new target turns out to also be a Lyman alpha quasar, at least 
you'll get two passes on each.


    (b) two quasar targets, both are confirmed z>2.1 and both have NOBS_MORE>1.  
    Do we choose to observe one quasar for all remaining epochs or do we divide the 
    remaining fiber assignments between the two quasars?  
    ****Proposal:  aim for equal number of fiber assignments with remaining layers.  
    LOGIC:  deeper spectra hit diminishing returns after two observations.  
    Better to divide the available fibers between the two targets rather than push one 
    target into diminishing returns.

This looks like a good general idea, except that (as Martin pointed out) not all quasars 
are as valuable. More on this below.

    (c) two LRG targets, one is z>20 and has one observation, the other is z>20 and has no observations.  Do we continue to observe the first target or do we prioritize the new target?  ***PROPOSAL:  Continue to observe the first one to 2X depth.  LOGIC:  Completeness of z>20 LRGs is supposed to be achieved by 2-pass observations.  Dividing time between the two reduces the likelihood that any one object gets the two passes.

For a second I was quick shocked when I read z>20 :-)   Jokes aside, it seems reasonable.

    (d)  two LRG targets, one is z>20 and has one observation, the other is z<20 and has no observations.  Do we continue to observe the first target or do we prioritize the new target?  ***PROPOSAL:  Continue to observe the first one to 2X depth.  LOGIC:  Completeness of z>20 LRGs is supposed to be achieved by 2-pass observations.  Two-pass observations likely to be high redshift where n(z) is dropping for LRG.  Invest time in object that likely constitutes a larger fraction of the number density at its redshift.

    (e) two BGS targets, one is observed but not confirmed, the other is not observed (I still think we should impose mag limits for NOBS).  ***PROPOSAL:  observe the new target.  LOGIC:  I think this is the BGS proposal anyway

    (f)  other conditions that we are forgetting?

(f) on the first pass, we have a BOSS z>2.1 quasar, and a quasar target that was not 
observed in BOSS (this might also be an issue with LRGs if we decided to reobserve them).
PROPOSAL: we observe the non-BOSS quasar in the first pass. 
LOGIC: If it was a BOSS quasar it is probably bright enough that we will get a good spectrum with only two passes. This of course assumes that in (b) we decide to split 2 and 2.

About quasar target values. There are three main things to consider:
 - probability of being a high-z quasar (as given by Redrock, QuasarNET or others)
 - its magnitude 
 - its redshift (z=2.1 have very few Lya forest pixels in the DESI spectrograph).

Ideally, one would take this into account, but I understand that this makes the code 
more complicated. Before spending more time on this: how often will this happen? 
(a) might happen quite often, but I'm not sure about (b). Does anyone has this number?

For the discussion in (b), we have already confirmed that both are high-z quasars. 
I would claim that the magnitude should not be that important, because even though 
it is true that bright quasars are more valuable (have lower noise), it is also true that 
the value of extra exposures is not as large. 
On the other hand, redshift does matter. In order to keep things simple, I would suggest 
to split the exposures into the two quasars, but with a priority on the highest-z quasar 
in case of a tie in the number of observations.

Somewhat related to this discussion: more often than not, we will not have 
"confirmed z>2.1" quasars, but instead we will have a probability for a quasars target to 
be a quasar at z>2.1. At least this will be the output of Redrock / QuasarNET / any classifier. 
I guess the default policy would be to choose those 50 targets / sq.deg. that have higher 
probability and consider them "confirmed". This has two problems:
 - the classification might change after the second pass, and a "confirmed z>2.1" might 
be classified as low-z or galaxy in the next fiber assignment (that might be ok).
 - more importantly, we are giving the same importance to a target with 99% probability 
of being a z>2.1 quasar and a target with 35% that made it to the list of 50 because may 
be there are a lot of stars in that area, or may be cosmic variance resulted in a low 
fluctuation in the number of true quasars in that area.

I understand that having continuous variables might be an issue in fiber assignment. 
If that is the case, we could have two (or three) bits to distinguish QSO_HIGHZ_SURE and QSO_HIGHZ_MAYBE (or _GOLD, _SILVER and _BRONZE). 
In that case we could be a little bit more efficient in selecting the right targets for fiber assignment.

Best,
Andreu

**Comment by geordie666** [comment]
Documenting discussion from today's Lyman-alpha telecon. We agreed to a set of _default_ decisions for the code, which I will implement. These defaults will likely change over the next few months as people further study metrics for optimizing priorities for Lyman-alpha reobservations.

------------------------------------------

**CASE:** Two quasar targets, one is confirmed `z > 2.1` with only one epoch and the other has not been observed.  Do we choose deeper observations of the known `z > 2.1` quasar or do we choose to increase sample size by taking an epoch of the unknown quasar target?

**DECISION:** Assign the fiber to the unobserved quasar - We then get a 3-1 split if that unobserved quasar is a tracer, or a 2-2 split if it's a Lyman-alpha quasar.

------------------------------------------

**CASE:** Two quasar targets, both are confirmed `z > 2.1` and both have `NUMOBS_MORE>1`.  
Do we choose to observe one quasar for all remaining epochs or do we divide the remaining 
fiber assignments between the two quasars?

**DECISION:** Equalize the number of fiber assignments. 

_NOTE_: This should be the current behavior as two such targets will have the same `PRIORITY` and fiberassign breaks the tie in favor of the target with higher `NUMOBS_MORE`.

------------------------------------------

**CASE:** A quasar target is flagged as having a warning (`ZWARN > 0`) in the spectroscopic redshift catalog. Should we treat it as "unobserved", or treat it as "done"?

**DECISION:** Give it a slightly lower priority than an "unobserved" target (so `MORE_ZWARN < UNOBS`)

**Comment by geordie666** [comment]
Addressed in #619.
