### ISSUE TITLE
mocks for bright time (BGS + MWS)

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#50]
@crockosi @apcooper @moustakas I've just started in the ```mocks``` branch the submodule ```mocks.brighttime``` to create target files consistent with [```quicksurvey```](https://github.com/desihub/desisim/blob/master/py/desisim/quicksurvey.py). 
Any help is appreciated to understand how have you been generating mocks so far. I believe you have been doing this separately, that is running fiberassign either on BGS or MWS targets, without having a joint set of targets mixing these two classes. Right?
We also need your input to decide how to  set the [number of observations](https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L92) for those targets.

**Comment by apcooper** [comment]
Hi Jaime,

No, for the MWS tests I'm creating mocks that combine both BGS and multiple types of MWS targets into one target list. Will add more details tomorrow but for now you can take a look at these two pages on the wiki:

https://desi.lbl.gov/trac/wiki/MilkyWayWG/FiberAssignment
https://desi.lbl.gov/trac/wiki/MilkyWayWG/GalfastExamples

**Comment by forero** [comment]
Hi Andrew, Thanks! 

I couldn't find on the wiki the explicit filename of the data and scripts that you used.

I assume that the stars correspond to the files here: https://virgodb.cosma.dur.ac.uk/DESI_data/milkyway/galfast/alpha/0.0.4/stars/ Is that right?

What BGS catalog did you use ?  
Where can I find the script that you used to put these two catalogs together?

**Comment by apcooper** [comment]
Yes, that's the right location/files for the MWS mocks I'm using right now. 

The BGS mock I'm using is based on the MXXL simulation. I think it's still work in progress from the BGS side, but suitable for MWS purposes at least. I don't know if its authors (Alex Smith and Shaun Cole) have published it to the collaboration yet. 

The scripts that I use to combine these catalogs are local to me; I'll send them to you in due course. Since the mocks are huge and their format and 'ancillary' data (star/galaxy properties) are very different, I do the 'target selection' / reduction to MTL format for each separately and then combine the resulting MTLs.

**Comment by forero** [comment]
Thanks, Andrew. I will start then looking for other BGS catalogs waiting for the MXXL mocks to be released. Looking forward to take a look at your scripts to understand what's the important information for you.

**Comment by apcooper** [comment]
Hi Jaime -- I've put my mock-making scripts up here: https://github.com/apcooper/mws_mtl_maker

The structure of those scripts might not be that intuitive but the basic idea is extremely simple, because the MWS (and BGS) selection function is currently so -- just a simple magnitude cut. Most of the code is therefore just reformatting some subset of whichever mock (which could be any old format: hdf5, fits, csv., etc.) to the MTL fits format.

As per the README, the procedure is to run `convert_to_mtl` separately for each input mock ('source') and then run `combine_mtl` on a bunch of those MTL files.

The important stuff is happening in [this loop](https://github.com/apcooper/mws_mtl_maker/blob/2982840fafddcffaf809da29ebd55ccb7ee134e2/convert_to_mtl.py#L123). The functions called e.g. to generate unique target IDs are specific to each mock and stored as classes defined in separate files (one file per mock source, although some mocks have multiple subclasses within one file). The most important one for MWS is [`mock_galfast`](https://github.com/apcooper/mws_mtl_maker/blob/master/mock_galfast.py]).

Note that the priorities and categories are hardcoded into the various mock classes and there is no attempt at sanity checking. Also the schemes for these numbers are my own system, not the collaboration standards. 

The mocks are already roughly tailored to the footprint so there's not much loss from just letting fiberassign sort out which targets are reachable, so there's no spatial selection.
 
Hope you can figure something useful out from this. Would be good to discuss this in Durham if you'll be there.

**Comment by forero** [comment]
Andrew, this is wonderful. Thanks a lot. I will start porting the details of the MWS mocks into the desitarget.mock and desisim.mtl submodules. I will be in Durham. We will have time to discuss the details.

**Comment by forero** [comment]
@apcooper please take a look at the ```mocks``` branch. Here are all the changes: https://github.com/desihub/desitarget/compare/mocks 

I need your help testing the main script https://github.com/desihub/desitarget/blob/mocks/bin/mock_targets_brighttime
 
The script has a ```-h``` for you to see the required inputs. Please let me know if something does not work for you.

**Comment by apcooper** [comment]
Apparently a small typo, given Python 3 (which I'm not that familiar with):

```python
@@ -46,7 +46,7 @@ def build_mock_target(root_mock_mws_dir='', output_dir='',
     # read the mocks on disk
     mws_data = desitarget.mock.io.read_mock_mws_brighttime(root_mock_mws_dir=root_mock_mws_dir)
     mws_keys = mws_data.keys()
-    n = len(mws_data[mws_keys[0]])
+    n = len(mws_data(list(mws_keys)[0]))
     
     # perform magnitude cut 
     ii = ((mws_data['SDSSr_obs'] > mag_bright ) & (mws_data['SDSSr_obs'] < mag_faint))
```

Other than that, works fine, produces reasonable-looking target.fits and truth.fits from my local copies of the MWS mock input. 

I did this with a local build of desiutil, desitarget and desispec from the latest default branches on github.

**Comment by sbailey** [comment]
We're not officially trying to support python 3.x yet, but this one is simple enough we should include it since we'll need to do it for the python 3 transition later this summer anyway.  I'd suggest:
```
mws_keys = list(mws_data.keys())
```
to directly make it a list in the first place.

For those who care about details, `mws_data.keys()` returns a list that can be indexed in python 2.7, but returns an iterator in python 3.x.  The iterator is more memory efficient if you are just looping over the keys, but if you actually want to index it you have to cast it to a list first.

**Comment by forero** [comment]
A basic version of MWS and BGS mock targets exists now.
