### ISSUE TITLE
spectroscopic truth region wish-list for DECaLS/DR3

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#52]
Row-matched DECaLS/DR2 catalogs of objects in the [spectroscopic truth regions](https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetingTruthTables) were compiled and documented in [this TechNote](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1595).

For DR3 we need to update these catalogs but also add:
- The [updated COSMOS photoz catalog](http://cosmos.astro.caltech.edu/page/photoz);
- The [DES SVA1 Gold catalog](https://des.ncsa.illinois.edu/releases/sva1/doc/gold);
- The [Spitzer data from the SHELA survey](http://irsa.ipac.caltech.edu/data/SPITZER/SHELA);
- What else?

**Comment by kdawson1000** [comment]
An obvious catalog to match would be the VVDS spectroscopic catalog.  The regions VVDS-F2217+00 and VVDS-F0226-04 are covered by the deep grz imaging from DES .  Data can be downloaded from here:
http://cesam.lam.fr/vvdspub/vvds_download.php

Beyond truth tables, we should match the specobj file from SDSS DR13, which will be public in early August.  We should also match the LOWZ, CMASS, quasar, and eBOSS targets so that we can identify objects that were not observed.  The BOSS targets are already public, the eBOSS targets are supposed to be public in DR13 but there may be a glitch.

**Comment by moustakas** [comment]
Also add [GAMA/DR2](http://www.gama-survey.org/dr2).

**Comment by moustakas** [comment]
Also add SDSS-I/II quasars (as requested by @imcgreer but assigned to @geordie666).

Quoting from [decam-data 1746]:
```
Ian's correct. Only about 25,000 of the SDSS-I/II quasars appear to be in DR12Q.fits.

As an alternative to matching increasing numbers of individual files...I have one large file of 
quasars that contains quasars/AGN from these surveys:

 0 SDSS
 1 2QZ
 2 2SLAQ
 3 AUS
 4 AGES
 5 COSMOS
 6 FAN
 7 BOSS
 8 MMT
 9 KDE !!!photometric only
10 XDQSOZ !!!photometric only
11 PAPOVICH
12 GLIKMAN
13 MADDOX
14 LAMOST
15 VHS
16 MCGREER
17 VCV !!!not necessarily visually inspected
18 ALLBOSS !!!not necessarily visually inspected (Superset_DR12Q)

that we could match to as a single file. The documentation's a little tricky (the file tries to 
track redshifts from *every* survey, so the user has to choose how to resolve redshifts from 
an array), but I could write that documentation up...

Cheers,
Ad.
```

**Comment by djschlegel** [comment]
If targeting doesn't have a need of matching to every other QSO survey in the world, then we might be better off not trying to do so as an input to DESI targeting.  There are just lots of details with each catalog, and those will be a moving target.  If there's a desire to have this, I'd suggest splitting into those data that could influence DESI targeting, and everything else.

The various SDSS QSO catalogs (and also the galaxy catalogs) will have various astrometric offsets from truth that we likely want corrected for any input to DESI targeting since those can amount to a large fraction of an arcsec.

**Comment by moustakas** [comment]
These catalogs are all intended for target selection training, not targeting itself.

**Comment by moustakas** [comment]
There was also a request (from Jeff Newman) to include the fluxes from multiple models in the truth regions (e.g., the SIMP fluxes for objects classified by Tractor as PSF, etc.).  This is just a reminder to do this once DR3 is out the door.

**Comment by janewman-pitt-edu** [comment]
Note: one needs to be careful in using VVDS -- a relatively small fraction of galaxies (~40%) have secure redshifts, including ~none past z=1.  It may be useful for picking out stars, though, they have plenty of those in their sample...

**Comment by moustakas** [comment]
VIPERS just had its [second public data release](http://vipers.inaf.it/rel-pdr2.html).  See also [desi-targets 1352].

**Comment by janewman-pitt-edu** [comment]
I've already discussed this with @rongpu and he's looked into doing the truth tables.  I don't _think_ they're complete, but they might be.  He's putting his files at NERSC.

**Comment by moustakas** [comment]
Updated catalogs have been generated as documented [here](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1595) (thanks to @rongpu!).  Please reopen an issue if you find you need additional truth regions matched.
