### ISSUE TITLE
Gaia catalog density cuts vs. l,b not just b

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#541]
Rather than a simple cut on galactic latitude, Boris suggests the following cuts to the Gaia target catalog to allow ourselves to get closer to the plane without overwhelming ourselves with target density.

![image](https://user-images.githubusercontent.com/218471/65536123-a29b9f00-deb7-11e9-9148-7d2665027de1.png)
![image](https://user-images.githubusercontent.com/218471/65536127-a4fdf900-deb7-11e9-8f52-b2e7b6833b4c.png)

**Comment by geordie666** [comment]
I've already embarked on a branch where I split GFAs and skies by HEALPixel so that we genuinely have all-sky catalogs. As part of that branch I will make sure that I also provide code so target classes can be read as a function of tile. This neatly solves some I/O slowness while maintaining the possibility of placing a tile anywhere on the sky.

But, Boris' work should be extremely useful in determining where we should or should not place *tiles*.

**Comment by geordie666** [comment]
Addressed in #548 and #558.
