### ISSUE TITLE
PRIORITY_INIT_[DARK/BRIGHT] conflict with make_mtl?

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#545]
It seems that the default now is to split `NUMOBS_INIT` and `PRIORITY_INIT` in to separate `DARK` and `BRIGHT` columns -- at least I think so, but I couldn't find any explanation of why.  For example, the `darkbright=True` here hardcodes that:
https://github.com/desihub/desitarget/blob/b6caaa3dfbf3968368415f8a618a755f662fe2d9/py/desitarget/cuts.py#L2297-L2299

However `make_mtl` still seems to want the original columns:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-61-2b7cdda6d656> in <module>
     24 
     25     print('Computing MTL...')
---> 26     pmtl = desitarget.mtl.make_mtl(pdata, obscon='BRIGHT|GRAY|DARK', scnd=sdata)
     27     
     28    

~/desi/code/desitarget/py/desitarget/mtl.py in make_mtl(targets, obscon, zcat, trim, scnd)
    128     # ADM use passed value of NUMOBS_INIT instead of calling the memory-heavy calc_numobs.
    129     # ztargets['NUMOBS_MORE'] = np.maximum(0, calc_numobs(ztargets) - ztargets['NUMOBS'])
--> 130     ztargets['NUMOBS_MORE'] = np.maximum(0, targets_zmatcher['NUMOBS_INIT'] - ztargets['NUMOBS'])
    131 
    132     # ADM need a minor hack to ensure BGS targets are observed once

ValueError: no field of name NUMOBS_INIT
```

The same thing happens with the secondary targets by default, although it just takes an extra command line toggle argument in `bin/select_secondary` to turn it off.

It's easy to make this not happen for the primary targets too, but since it's hardcoded I feel like I'm missing something about why this `DARK`/`BRIGHT` split is happening. How should target files with that split be carried forward to the MTL?

**Comment by geordie666** [comment]
@apcooper: Thanks for your efforts on checking the secondary targets. It's really helpful to have someone working on this.

When writing the primary targets, the `_INIT_BRIGHT` (etc.) columns are removed as part of the function _bright_or_dark():

https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L271

Specifically here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L315-L325

I thought this was already also being done in `select_secondary`. For instance, here in the code:

https://github.com/desihub/desitarget/blob/master/bin/select_secondary#L61-L64

we request that `io.write_secondary()` runs once for `DARK|GRAY` conditions and once for `BRIGHT` conditions, and then in `io.write_secondary` we discard the `_INIT_BRIGHT` (etc.) columns here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L568-L569

In any case, the goal should be files in two output directories. A "bright" and a "dark" directory, like this at NERSC:
```
/project/projectdirs/desi/target/catalogs/dr8/0.32.0/targets/sv/resolve/
```

Perhaps your issue is because you're running the functions rather than the command line arguments? Or, I could easily have introduced a bug somewhere...

**Comment by apcooper** [comment]
OK, thanks for the helpful explanation -- in the end this was my fault. I was using `--writeall` (which makes a file combining dark and bright targets with the same name, one level up from the '/bright' and '/dark' subdirs) then passing that combined file to the MTL by mistake.

**Comment by geordie666** [comment]
Ah, gotcha. We retained `--writeall` in case we needed to go back to testing the old schema (writing things out without the bright/dark split). Apologies that it was misleading.

Close this issue if you're ready.
