### ISSUE TITLE
desitarget doesn't work with DR9b brick format

### ISSUE THREAD

**Issue by Cyeche** [desihub/desitarget#546]
All is said in the title:

select_targets --tcnames QSO --nosecondary /global/cscratch1/sd/yeche/Test_dr9b/ T.fits
INFO:select_targets:110:<module>: running on 32 processors
INFO:cuts.py:2207:select_targets: Running on the main survey
Traceback (most recent call last):
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 377, in get
    return Q.get(timeout=1)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 674, in map
    capsule = pg.get(R)
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 380, in get
    raise StopProcessGroup
desitarget.internal.sharedmem.StopProcessGroup: StopProcessGroup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/y/yeche/desitarget/bin/select_targets", line 138, in <module>
    resolvetargs=not(ns.noresolve), mask=not(ns.nomaskbits)
  File "/global/homes/y/yeche/desitarget/py/desitarget/cuts.py", line 2353, in select_targets
    targets = pool.map(_select_targets_file, infiles, reduce=_update_status)
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 678, in map
    raise pg.get_exception()
desitarget.internal.sharedmem.SlaveException: could not broadcast input array from shape (4333,6) into shape (4333,5)
Traceback (most recent call last):
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 265, in _slaveMain
    self.main(self, *self.args)
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 563, in _main
    r = realfunc(work)
  File "/global/homes/y/yeche/desitarget/py/desitarget/internal/sharedmem.py", line 629, in realfunc
    else: return func(i)
  File "/global/homes/y/yeche/desitarget/py/desitarget/cuts.py", line 2309, in _select_targets_file
    objects = io.read_tractor(filename)
  File "/global/homes/y/yeche/desitarget/py/desitarget/io.py", line 186, in read_tractor
    data[col] = indata[col]
ValueError: could not broadcast input array from shape (4333,6) into shape (4333,5)

**Comment by geordie666** [comment]
I'm currently working on a large branch that is needed for commissioning next week, and that uses DR8 files as input. Once I'm done with that branch and have tagged the code, I'll update the I/O functions to recognize changes to the data model for DR9. Probably by Monday.

**Comment by geordie666** [comment]
@dstndstn : This error appears to be triggered by the `DCHISQ` column, which was `('DCHISQ', '>f4', (5,))` in DR8 but appears to be `('DCHISQ', '>f4', (6,))` in DR9b. Is this a deliberate choice? 

I know you've been working on Sersic profiles, but I thought the idea was to substitute those instead of `COMP` rather than having an additional profile.

If this _is_ a deliberate choice, in what order are the 6 profile entries in `DCHISQ`, now? I tried to find this in legacypipe, but (in master) it looks like there [should still only be 5](https://github.com/legacysurvey/legacypipe/blob/088c57f6314d8a59ed8557186b732f3ee44e6467/py/legacyanalysis/fix-model-selection.py#L37-L41). Maybe.

Did `DUP` perhaps slip in as an extra `TYPE` that is now in `DCHISQ`?

**Comment by dstndstn** [comment]
This was on purpose; while testing, SER and COMP are both still there.

**Comment by geordie666** [comment]
@dstndstn : Will they vanish for DR9 "proper" (so I don't need to include them in the data model)?

And, what is the ordering? Is SER added as the final entry (which would mean that current indexing would work as-is for current target selections)?

**Comment by dstndstn** [comment]
Yes, in DR9 proper, I'm hoping to switch to SER and drop COMP.

Yes, SER is the last entry.

**Comment by geordie666** [comment]
@Cyeche : As this is just a testing change that won't be permanent in DR9, I suggest that we don't make changes in the main desitarget code. Locally, you can just change this single line in `desitarget.io()`:

https://github.com/desihub/desitarget/blob/7b2a4c2fc3b9d9cd7157b655cdef4f1d19660abb/py/desitarget/io.py#L45

To be:
```
    ('DEC', '>f8'), ('DEC_IVAR', '>f4'), ('DCHISQ', '>f4', (6,)), ('EBV', '>f4'),
```
instead of:
```
    ('DEC', '>f8'), ('DEC_IVAR', '>f4'), ('DCHISQ', '>f4', (5,)), ('EBV', '>f4'),
```
and everything should then work for you. If you agree, close this issue. If you'd prefer, I can create a branch with this single change for people to checkout and use, and we'll just never merge that branch into master.

**Comment by Cyeche** [comment]
I would prefer that you create a branch that we reset later.

Thanks, Christophe.

**Comment by geordie666** [comment]
Done:

https://github.com/desihub/desitarget/tree/ADM-dr9b-test

I'm sure you already know this, but to run, checkout the branch as follows:

```
git checkout -b ADM-dr9b-test
```
and then run `select_targets` or `select_sv_targets` as normal.

**Comment by geordie666** [comment]
Addressed by spawning the `ADM-dr9b-test` branch.
