### ISSUE TITLE
consider adding obscon to target files

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#557]
Spinning an off-list discussion with @sbailey and @geordie666 into an issue, the proposal is to explicitly include `obscon` in the target filenames i.e.,
`targets/dark/targets-*.fits`
would become
`targets/dark/targets-dark-*.fits`

And ditto for `bright` targets and the mock output files.

**Comment by sbailey** [comment]
Related: currently `desitarget.io.write_targets` and `_bright_or_dark` do some rearrangement of the directories (and filenames?) to get the obscon and healpix numbers in there.  We need something like `findfile` that can reconstruct the canonical filepath given input like base directory, nside, healpix, obscon, etc.  Currently that is in `desitarget.mock.io.findfile`, but that isn't actually specific to mocks and it would be better for `desitarget.io` to provide that directly and mocks and desisim just use it.

**Comment by geordie666** [comment]
Also related: Howsoever this `findfile` function is written, it would be convenient to have it stop at the directory-level if `healpix` is passed as `None`.

This is because the `desitarget.io.read*` convenience functions (`read_targets_in_hp`, `read_targets_in_tiles`, etc.) operate at the directory-level.

I can get to this on Monday, if nobody beats me to it.

**Comment by geordie666** [comment]
Addressed in #558.
