### ISSUE TITLE
What tag/release are we on?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#58]
I (think I) need to create a new release of ```desitarget``` so the Travis tests for https://github.com/desihub/desisim/pull/132 can complete.  However, https://github.com/desihub/desitarget/releases shows that even though 0.3.3 (which is what ```.travis.yml``` in ```desisim``` currently depends on) is the current release, @kaylanb tagged a version 0.4.0 on July 12.  

Shouldn't we be on 0.3.4 or were the changes introduced by @kaylanb significant enough to bump us to 0.4.0?  And if so, shouldn't this become the "current release" of desitarget?

@sbailey Can you advse on what we should do (and specifically so the  https://github.com/desihub/desisim/pull/132 tests can complete)?

**Comment by weaverba137** [comment]
In GitHub land, "releases" are tags with a little extra documentation.  You really want to look at https://github.com/desihub/desitarget/tags.

As far as 0.3.4 versus 0.4.0, that I don't know.

**Comment by sbailey** [comment]
I cut a new "release" for tag 0.4.0; in practice just pay attention to the latest tag number even if we haven't officially drafted a release for it.

Guessing that John's changes are more than a bug fix, the next tag/release would be 0.5.0.  If the change is really minor it could be 0.4.1.

In principle starting from `x.y.z`, `x` gets updates for non-backwards compatible changes, `y` gets updated for new features that are backwards compatible, and `z` gets updated for bug fixes.  In practice I'm holding off on updating `x` beyond 0 since "1.y.z" implies a level of maturity that we haven't yet achieved, so `y` is updated for any major change, whether it is backwards compatible or not.

**Comment by sbailey** [comment]
And I cut 0.5.0 tag+release, which I think is what is needed for desisim.

**Comment by kaylanb** [comment]
Thanks Stephen. 

`0.4.0` added the DR2 code that creates the tables for the psql database and uploads tractor catalogues. I'll add `0.6.0` or `0.7.0` soon for the DR3 version.

**Comment by moustakas** [comment]
Release 0.5.0 is exactly what I need -- thanks.
