### ISSUE TITLE
consider using module-level variables for bright and faint magnitude limits for each target class

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#618]
Ticket spun off from https://github.com/desihub/desisim/issues/507 (see especially [this comment](https://github.com/desihub/desisim/issues/507#issuecomment-626190280)).

A periodically recurring issue is that as the targeting cuts for the various classes evolve, the magnitude priors on the templates used for integration testing slip out of the allowed / allowable ranges, which manifests in an odd and somewhat hard-to-track-down way in `desisim` (like "low flux" for a given target class).

One possible solution would be to have `desisim.templates` import the bright and faint magnitude/flux cuts directly from `desitarget.cuts` for each target class, although I'm sure there are other possibilities.

**Comment by geordie666** [comment]
Is this simply a question of magnitude cuts, or is this going to happen *any* time a target falls outside of an allowed range?

For example, say target-type X has a color cut `g-r < 1.0`. And then we change that to `g-r < 0.5`. Could such a change in color cuts also mean that templates slip outside of the allowed ranges?

If the issue is just the magnitude ranges, then I'd agree that we could just include those as common variables in `desitarget.cuts()`, `desitarget.sv1.sv1_cuts()` (etc.). But, if it's a wider issue that the templates could fall outside of parameter ranges *in general* then I'd argue for instead catching exceptions in `desisim`.

**Comment by moustakas** [comment]
Just magnitude cuts. If I've done my job, the *possible* templates will always span a broader range of color than the color-cuts we apply in `desitarget.cuts`. If that's not the case, then the DESI templates are inadequate for our work and will need to be updated.

**Comment by geordie666** [comment]
In that case, I think I agree with module-level constants. There's probably a slicker way of doing it, but module-level constants seem straightforward. Leave this with me.

**Comment by geordie666** [comment]
@moustakas: I started to look at this and hit a roadblock. The LRGs don't _have_ an explicit bright limit, see, for instance [the wiki page](https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection#LuminousRedGalaxiesLRG). Masking on `MASKBITS` prevents the LRGs from observing bright targets.

If there isn't an alternative way for `desisim.templates` to determine a sensible bright-end prior, and if @rongpu doesn't want to switch over to having a bright-end magnitude cut, then I have 3 questions for @moustakas before I proceed with addressing this issue. First, relatedly:

- What should I do when a selection for a given target class doesn't explicitly have a bright or faint limit (the LRG problem)?

and then, also, to help me to determine how deeply to dive into any refactor of the code:

- Do you need this refactor for SV as well as the Main Survey, or does `desisim.templates` just care about the Main Survey?
- Do you need this refactor for all target classes (MWS targets, backup targets, etc.) or just for the "large-scale structure" target classes (BGS, ELG, LRG, QSO)?

**Comment by rongpu** [comment]
> Masking on MASKBITS prevents the LRGs from observing bright targets.

Although it says "Star/bright obj. masking" on the wiki, it's really just bright star + LSLGA. I don't think it removes other bright targets?

The current LRG selection does not have a bright-end magnitude cut (there used to be a bright cut but we have since removed it based on input from the C3 group), and it is intentional –– the brightest LRGs are also the most massive galaxies, and we want to keep them in LRG sample.

**Comment by moustakas** [comment]
@geordie666 thank you for taking the time to work on this. I agree that what I've proposed is not ideal since it varies from target class to target class. I wonder if `desisim.templates` should raise an exception rather than just issue a warning when a spectrum cannot be generated, i.e., when the latest color-cuts can't be satisfied. That should prevent the kinds of second- and third-order problems (like "low QSO flux") that are hard to track down. If you and/or @sbailey agree, I'll implement this in `desisim.templates` and let's leave `desitarget` alone.

**Comment by geordie666** [comment]
@moustakas: Just throwing an exception in `desisim.templates`, with an informative message to suggest checking the bright-end magnitude, etc., sounds sensible to me!

**Comment by geordie666** [comment]
@moustakas: I think we can close this. Do you agree?

**Comment by moustakas** [comment]
Yes, let's do this in desihub/desisim#537.
