### ISSUE TITLE
failed srun over mpi_select_mock_targets

### ISSUE THREAD

**Issue by sierraporta** [desihub/desitarget#628]
I was running mpi_select_mock_targets like so:
srun -N 2 -n 16 -c 8 -C haswell -t 01:00:00 mpi_select_mock_targets --no-spectra --nproc 60 --nside 16 --seed 10 -c dark-mock-targets.yaml &

It starts by calculating well and creates the usual folders where the targets will be written, but after several minutes (~ 10) it gives me an error:

srun: Force Terminated job 32233190
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 32233190.0 ON nid01934 CANCELLED AT 2020-07-03T02:59:56 DUE TO TIME LIMIT ***
srun: error: nid01934: tasks 2,4-5,7: Terminated
srun: Terminating job step 32233190.0
srun: error: nid01935: tasks 8-15: Terminated
srun: error: nid01934: tasks 0-1,3,6: Terminated

if I add the -t 01:00:00 option in first line, then it gives the following error:

srun: error: Unable to allocate resources: Requested time limit is invalid (missing or exceeds some limit)

Has anyone run this or know what might be happening?

**Comment by alxogm** [comment]
Hi @sierraporta  it seems you haven't specified the queue to submit the job. It then is trying to send your job with the default, i.e.  to the debug queue and gives it 10 minutes. That is why it stops in the first case, in the second case it stops because the debug queue allows for a maximum of 30 min.  All this is here: https://docs.nersc.gov/jobs/

Also, I think you are not specifying the tiles or pixels to process, so I think your process will eventually stop due to memory error or time limit. If you are only testing/learning how to produce mocks, pass a few pixels only...
