### ISSUE TITLE
Documentation builds and other imports trigger IERS download

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#674]
It is likely that an import of something from astropy is triggering a download of IERS leap second data at import time instead of at run time:
```
weaver@BOSS[28]: sphinx-build -W --keep-going -b html doc doc/_build/html
Running Sphinx v3.2.1
Downloading https://www.ietf.org/timezones/data/leap-seconds.list [Done]
making output directory... done
loading intersphinx inventory from http://docs.python.org/objects.inv...
...
```

**Comment by geordie666** [comment]
@weaverba137: I've managed to dig into this a little. Although there _are_ some module-level imports of `astropy.coordinates` in `desitarget`, the main culprit here seems to be `healpy`, which must itself import `astropy`. Here are some options:

1. I could use `from desiutil.iers import freeze_iers` and then `freeze_iers()` at the module-level before I `import healpy as hp`. That's easy enough to code-up but it contravenes PEP 8 style because subsequent module-level imports are not at the top of the module file.
2. I could only use `import healpy as hp` inside of functions, but `desitarget` uses `healpy` _a lot_ so that would be messy, hard to maintain, and inefficient.
3. We just ignore the IERS download and hope this is fixed in a later version of astropy.

Inaction (3.) seems as palatable to me as the other options, unless you have a better approach.

**Comment by sbailey** [comment]
Indeed, it would be really nice if astropy would fix this themselves by providing a way to turn off downloading without asking.

**Comment by weaverba137** [comment]
I'll see if there's already a healpy ticket on this. Maybe it can be fixed there.

Is it possible to avoid the problem by only importing the functions actually used, instead of the entirety oh healpy?

**Comment by geordie666** [comment]
I haven't tested every `healpy` function, but some of them certainly trigger the download in-and-of-themselves, e.g. (after removing the `astropy` leap-second cache):
```
from healpy import pix2ang                                                                                                                                                                       
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|=========
```

**Comment by weaverba137** [comment]
PS, one other thing to consider: the documentation *should* be able to build in an environment where healpy is entirely absent. This is done by the equivalent of `unittest.mock` to make imports succeed even if the package is absent.  Has this been tried? There are many examples in the configuration of other DESI packages.

**Comment by geordie666** [comment]
This has _not_ been tried. But, downloading leap-second data is a problem for the code in general, not just for the documentation builds. So, I'm hoping there's a more general solution that also fixes the doc builds.

**Comment by weaverba137** [comment]
Sure, but maybe the title of the issue should be changed to reflect that we want this stopped in *all* situations.

**Comment by geordie666** [comment]
Could do, sure. Feel free to change it, if you'd like.

**Comment by weaverba137** [comment]
OK, but please be advised that I probably won't have time to work on this until next week or possibly April.

**Comment by weaverba137** [comment]
@geordie666, I haven't seen this in recent tests.  Is this still being seen frequently?

**Comment by geordie666** [comment]
I see it occasionally, but not frequently. If it's still there, it's not really impacting any work, as far as I can tell. If you want to close this issue, feel free to do so.

**Comment by weaverba137** [comment]
I have not seen this in a long time, even after I've watched a lot of tests of `desitarget` recently.
