### ISSUE TITLE
FiberAssign scripts in desitarget

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#70]
@sbailey @apcooper 

We have [this script to match fiberassign outputs to the input mocks to build the Target File](https://github.com/desihub/desitarget/blob/74c7a1feada143e9edefa1a31ca611628a9c805e/bin/fa_output_to_mocks.py). 

* The script uses the `mocks.io.fiberassign` submodule from `desitarget`. Should we instead move that module into `fiberassign/bin`?
* There are many ordering assumptions to make the matching (and avoid search/finding routines). Do we want to keep implicit assumptions (easy to break)? or do we want to go for explicit search/matching (more robust)?

We also have [this script to create directories and prepare a fiberassign run](https://github.com/desihub/desitarget/blob/c8aff8fa3b6c11a4c70ae88b123a14d6f96f7c1e/bin/setup_fa_run_dir.py). 

* Shouldn't we also have that in `fiberassign/bin`?

**Comment by rncahn** [comment]
I'd like them in fiberassign/bin

**Comment by sbailey** [comment]
This looks ok to move from desitarget into fiberassign.  Off the top of my head I think the split should be:
* preparing target catalog/mock inputs for fiberassign: desitarget
* manipulating/analyzing the outputs for fiberassign: fiberassign

Anything that a typical user of fiberassign would run from the command line should be in bin/ .  OK for specialized test scripts to be elsewhere if we *don't* want typical users to run them.  In general, the scripts should be lightweight wrappers around library functions/modules, which make re-using the library functions possible (e.g. from desisim wrappers).  This comes at the cost of having to get fiberassign/py into your $PYTHONPATH (and ditto for desitarget) so that the scripts can find the modules in there.  See https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines .

Can you give some specific examples of the ordering assumptions?

**Comment by apcooper** [comment]
Re. fiberassign, agree with @sbailey. Specific split of routines into those two categories follows. Will write separately about the ordering assumptions introduced in apc_mocks.

- preparing target catalog/mock inputs for fiberassign: desitarget
`make_mtls_for_sources` (specifically to build target lists from mocks)
`make_catalogs_for_source_files` (relies on targetids having a specific logic that makes sense for mocks only)

- manipulating/analyzing the outputs for fiberassign: fiberassign
`features_parse` (maybe a more comprehensive version of this exists somewhere already?)
`combine_targets_truth` (intended to work with any valid input to fiberassign)
`reduce_fiber_maps_to_mtl` (relies on specific logic for targetids assigned by `make_mtl` but independent of assumptions in mocks)

**Comment by apcooper** [comment]
apc_mocks introduces a few conventions intended to avoid the need to match very long lists of integers in the loop from ‘raw' mock catalogs -> target selection on mocks -> construction of MTL from individual target lists -> fiberassign output -> analysis of which targets got assigned and when. 

There is some explanation in the [docstring to `make_catalog_for_source_files`](https://github.com/desihub/desitarget/blob/apc_mocks/py/desitarget/mock/fiberassign.py#L181) (see also [ the doc to `make_mtls_for_sources`](https://github.com/desihub/desitarget/blob/apc_mocks/py/desitarget/mock/fiberassign.py#L45)for the distinction between target lists and the merged target lists). 

1. In the routines to construct TLs (one per mock) TARGETID is set to encode (in one int) the file and row number of the ‘raw’ mock from which the target originated. The file order is imposed in the mock reading routines by enforcing iteration over files in the order given by the python `sort` of their file names (default options to `sort`).

2. In `make_mtl` TARGETID is re-assigned to be equal to the row number of the target in the MTL. The previous TARGETID from (1) is stored in the truth file as ORIGINAL_TARGETID.

3. Since assignment of TARGETIDs to sky and standard targets is not done by `make_mtl`, the TARGETIDs for these special targets are required to be in a predefined range (start from some huge number) which consequently imposes a (large) upper limit on the number of rows in the MTL under (2).

Convention (2) means that the per-tile fiber maps created by fiberassign can be quickly mapped into the order of the input MTL, without having to match on TARGETID. 

Convention (1) means that rows in the MTL can be matched back to the order of the ‘raw’ mock files without having to read the mock again and match on TARGETID. This is specific to the analysis of mocks, and is used in [`make_catalogs_for_source_files`](https://github.com/desihub/desitarget/blob/apc_mocks/py/desitarget/mock/fiberassign.py#L181). (To avoid having to reconstruct the file sort order when interpreting `file number' in the mapping back from FA to the mock files, an explicit list of source files is stored in the Truth table associated with each target list -- this is somewhat ugly).

Both these conventions naturally enforce the uniqueness of TARGETID in the MTL and within the individual TLs. The convention of separate TARGETID ranges for real targets, skies and standards in the MTL is certainly fragile -- not sure how fragile the rest is. The convention in (1) could be broken by routines to read individual mocks, but that would only break the mapping back from the FA outputs — this would be a problem for the users of that specific mock only (the pipeline presumably proceeds with the MTL-assigned TARGETIDs). As well as being slow for very long lists, explicit matching can also be vulnerable to rogue duplicates and occasional quirks in comparison routines for different int types -- both tricky to spot and debug).

That said, I don’t think the above use of TARGETID is the best way to implement this -- for a quick implementation it seemed easier than introducing new columns to the target and truth format and the fiberassign output, but a more robust implementation should probably do both. Specifically:

- The use of TARGETID for (1) could be avoided by storing the file and row number in their own columns.
- The use of TARGETID for (2) could be avoided by having FA output the MTL row number explicitly in the FA tile outputs.

Finally, convention (3) is only partly implemented right now -- there currently isn't a routine to generate sky positions (randomly or otherwise) in this framework.

**Comment by forero** [comment]
Good. I will move the following scripts into `fiberassign/bin` 
`setup_fa_run_dir.py` (prepare directories for a fiberassign run -does not prepare files-)
`mocks_to_fa_input.py` (process fiber assign outputs)

**Comment by forero** [comment]
I agree there is a "purity" problem to solve. Either we mix `fiberassign` stuff into `desitarget` (as it is now) or we mix `desitarget/mock` stuff into `fiberassign` (as I suggest). I prefer the second option, i.e. `desitarget` should only include code to prepare `targets` not how to deal with `fiberassign` outputs.

**Comment by rncahn** [comment]
Jaime's comment sounds right to me.

"desitarget should only include code to prepare targets not how to deal
with fiberassign outputs. "

**Comment by apcooper** [comment]
OK! It's good to have a decision that fiberassign should include code supporting the workflow of running it on the mocks. I agree that's the most logical way, without a separate module. So @forero, you're also going to split the current `desitarget.mock.fibreassign` along the lines I suggested above?

**Comment by forero** [comment]
@apcooper Yes. I will do the splitting. I have already split the scripts in `bin`. Right now I am working in making py2->py3 changes into your code. Later on I will split routines.
