### ISSUE TITLE
main_cmx_or_sv() may incorrectly report 'main' instead of 'special'

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#813]
As it is currently written `desitarget.targets.main_cmx_or_sv()` does not have any visible way to distinguish between 'main' and 'special' surveys. What is the definitive way to identify survey = 'special'?

**Comment by geordie666** [comment]
`desitarget` has no concept of a "special" target. I think the "special" term first arises downstream and is attached to a type of _tile_ rather than a type of target, e.g.:

`more $SURVEYOPS/ops/tiles-specstatus.ecsv | grep special`

But, regardless, there are no "special" targets as far as `desitarget` is concerned.

Further context: The `main`, `cmx` or `sv` targets are identified via their respective targeting columns `DESI_TARGET` (for main), `CMX_TARGET`, `SV1_TARGET`, `SV2_TARGET`, `SV3_TARGET`. There is no `SPECIAL_TARGET` column.

**Comment by geordie666** [comment]
One other thought: It's possible that the term "special" for a tile is being conflated with the term "tertiary" for a target. Tertiary targets often end up on special tiles. Tertiary targets can be identified by having `RELEASE` bits equivalent to 8888 in their `TARGETID`, as described in section 3.2.3 of [the desitarget paper](https://arxiv.org/abs/2208.08518). But, again, I think "special" is a term related to a tile, not a target.

**Comment by weaverba137** [comment]
I think the need to identify main versus special specifically using `main_cmx_or_sv()` is now moot, so I propose closing this ticket.

**Comment by geordie666** [comment]
Agreed, thanks.
