### ISSUE TITLE
Encode mock provenance into TARGETID.

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#88]

**Comment by sbailey** [comment]
I'm not sure of the exact original intent of this issue, but adding some possibly related information:

* [DESI-2348](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2348) defines our draft TARGETID scheme, intended for both real data and hopefully mocks as well.
* This includes a bit for indicating that this is from a "mock data release"
and bits for indicating which release number.
* When the set of mocks converge for what we will use for the Dec2016 meeting, we should declare that set as "mock data release 1".
* We should also use the real brickID (20 bits reserved).
* `select_mock_targets` should also output a mapping of TARGETID to originalfile + row number if that can't be encoded in the scheme defined in DESI-2348.

For the December meeting we are focusing on a catalog based simulation, but we should make it as easy as possible for people to take our final catalog and match it back up to the objects in their original input mocks and the conditions under which we claim they were observed so that they could augment the run with spectra simulated for those objects under those conditions.

**Comment by sbailey** [comment]
Our current mock inputs come in several forms:
* GaussianRandom: 1 file per target class (ELG, LRG, QSO, random)
* MWS WD: 1 FITS file
* MXXL (for BGS): 1 HDF5 file
* galaxia: many files in a tractor-like brick hierarchy of subdirectories
* Lyman-alpha: 28 files with 50k HDUs each (!) in a single directory

Only the first 3 follow our original expectation of being able to trivially match a mock row number to TARGETID.

Options for tracking TARGETID back to its original mock input given the N>>1 files in a potential directory hierarchy:
1. Make others do the work: Request a new round of mock catalogs that assign MOCKID to their targets.  We would provide the mapping of TARGETID:MOCKID, but otherwise each group would be responsible for figuring how how to find a given MOCKID in an actual file.  We could use the upper byte of MOCKID to assign ranges of IDs per mock catalog class.
2. Brute force: Keep table with columns MOCKFILE, MOCKROWNUM, TARGETID .  The many many repeated MOCKFILE entrys would get rather verbose, but it is straighforward.
3. Fancy brute force: keep a mapping of MOCKFILE -> integer MOCKFILEID, and then a table of MOCKFILEID, MOCKROWNUM, and TARGETID.  Or MOCKFILEID + MOCKROWNUM could be combined into a single MOCKID.

In any of these scenarios, the header of our TARGETID:mock map should contain the version of the mocks uses as inputs.

**Comment by geordie666** [comment]
I like possibility 3, with a map of TARGETID:MOCKID. That way we keep control of how TARGETID is assigned, and can make the end-to-end process resemble our expectation for real targets.

**Comment by ngbusca** [comment]
For lyman-alpha, would it help to add a master file with a mockid, ra, dec, z, filename and header id of the corresponding spectrum? I can take care of that if it's useful. 

For the spectra files, should I change the hord of headers for a single sparse image?

**Comment by forero** [comment]
This is not addressed in the current implementation of `select_mock_targets`. Reopening.
